### ISSUE TITLE
can't send fotos anymore

### ISSUE THREAD

**Issue by w877** [tomlandia/fuckr#1]
Thanks for a great app. At first it worked like magic, now when I try to send a pic and click the plus sign, I can add the pic from my desktop, but nothing happens. It doesnt show the pics under the chat box. Also all my uploaded pics are gone. Pls help to resolve :)

**Comment by tomlandia** [comment]
Any clue how to reproduce haha :)?

**Comment by w877** [comment]
I think its either related to uploading several pictures. I think I had 5 there, when it stopped working. Or then with the page lengt in chat window. I have some long chat windows and when I go from one chat to another I have to always scroll all the way down... could it be that the pics are there under the + but they arent just visible in my screen.

**Comment by tomlandia** [comment]
I tested with 9 pics and it does scroll (the last two buttons are hidden if the pics are shown)... maybe try [version 1.0.1](http://fuckr.me/)?
