### ISSUE TITLE
Unexpected error (HTTP 400)

### ISSUE THREAD

**Issue by baronjuan01** [tomlandia/fuckr#101]
In the version of Fuckr installed on my laptop, this error causes the app to not open, and display the message "Unexpected error (HTTP 400). Check out http://fuckr.me/ for updates."

**Comment by RobbieTechie** [comment]
@baronjuan01 Did you bother to look at the site as the message suggested?  There have been updates and they are posted there.  There was no need to open this issue.

**Comment by RobbieTechie** [comment]
That's not a whole lot to go off of, which version are you currently working with?  And did you bother to check out http://fuckr.me/ like the message stated?

**Comment by guynwpg** [comment]
This is the same error I was getting with 1.8.0 and now with 1.8.1 as well.

I can still use 1.7.0, No problem but the later versions won't even let me log in.

**Comment by RobbieTechie** [comment]
I noticed in 1.8.1 the Fuckr.exe file itself is 58 Megabytes, normally it's a little over 1.  If you are on Windows 64 bit, try the one I'm attaching, it's still 1.8.1 but i put a fresh copy of Fuckr.exe and the files that go with it for Windows  64 bit in this zip file.
https://drive.google.com/file/d/0BxSmknffFGTnTFJWeU1qQTl4TEE/view?usp=sharing

**Comment by guynwpg** [comment]
OK, so this works perfectly.

I know you said it's 1.8.1 but I honestly can't tell any difference lol.

**Comment by RobbieTechie** [comment]
Basically, the higher the version means more code has been updated to work better.  I downloaded the one on fuckr.me and replaced some of the files. I'm glad it's working for you.

**Comment by guynwpg** [comment]
I stand corrected, it now shows the distance in miles and the links to social media now appear as well. Excellent!

**Comment by northstar77** [comment]
@RobbieTechie I downloaded 1.8.1 (For Mac) and I, too, am getting the a pop-up that says "Unexpected error (HTTP 400). Check out http://fuckr.me/ for updates." as soon as I open Fuckr and when I try to log in (which I'm not able to do). Help?

Thanks!

**Comment by bootyliciousgeek** [comment]
started to have this error after a few days on 1.8.1 win 64 bit. Even tried @RobbieTechie one. Older version is also affected. Guess this isn't specific to 1.8.1

**Comment by kusaa** [comment]
Started having this error this morning as well.  Did they update their APIs again?

**Comment by guynwpg** [comment]
Yup, getting the error again, something must have happened....

**Comment by kusaa** [comment]
Anybody else having this problem? @RobbieTechie is fuckr working for you?

**Comment by RobbieTechie** [comment]
Hey guys, 
Nope, it's not working for me either.  I know the app has errors when it tries to pull the nearby profiles.  It gives a 400 (bad request) and does not allow posting.  It could just be a server issue, but I'm not sure.
