### ISSUE TITLE
Old database not compatible with new installation 1.8.1?

### ISSUE THREAD

**Issue by mark-chat** [tomlandia/fuckr#103]
I just downloaded 1.8.1 into a fresh folder but when I launch it, it goes to a sign-in screen and when I sign in, my old profile database isn't retained and all of my old messages are deleted and I default to location of San Francisco.

Is there a way to keep all the old history?
(Thankfully I have a backup of my profile folders and when I restore these and then launch the 1,6 fixed version that was working prior to this, all of my old messages are still there)

**Comment by RobbieTechie** [comment]
@mark-chat Which operating system are you using?  I could re-create your problem on Win 7 64 bit.  It appears to be the version of Node Webkit.  If I used the version included with this release it would make you log in again, but if I download the version on NW site, it worked and logged right back in.  The link is here:
https://dl.nwjs.io/v0.19.5/nwjs-v0.19.5-win-x64.zip
Download, and extract that, the copy it in your folder, where you put version 1.8.1 and it should go, if you're on windows at least.

**Comment by mark-chat** [comment]
Thanks for the answer

Windows 10- 64 bit
The fix didn't work unfortunately.
The log on screen comes up and then immediately shuts down when I click on the email address box to try and login

**Comment by RobbieTechie** [comment]
That sounds like it's shutting down from when grindr forced the update to version 3,   I attached a file called package.json, had to put it in a zip file to attach.  Just unzip that and copy that file into your main fuckr folder,i where the Fuckr.exe or nw.exe file is, then try to launch the app again.
[package.zip](https://github.com/tomlandia/fuckr/files/721107/package.zip)

**Comment by mark-chat** [comment]
Sorry RobbieTechie but it still does the same and shuts down without letting me type in a password. It still comes up with a login screen.

Just to confirm - the version I can get to work is 1.7 with your patch files that you uploaded at the end of October

**Comment by RobbieTechie** [comment]
I just tested something.  I coped an version 1.7 that I messed with, put it in a new folder and ti worked fine.  Then I downloaded, extracted and copied the 1.8.1 to that folder overwriting everything.  When I ran it, it did like yours and wanted me to login.  The I downloaded the new nwjs from the site, but it didn't have the exe as fuckr.exe but as nw.exe, but worked.   I attached the exe file, unzip that and replace the Fuckr.exe with this one and see if that works.
[Fuckr.exe.zip](https://github.com/tomlandia/fuckr/files/721212/Fuckr.exe.zip)

**Comment by RobbieTechie** [comment]
So the entire 1.8.1 seems to be messed up from the executable, it's 58 megabytes, and normally a little over 1.  I don't know if it just got compiled bad or what happened, but here is version 1.8.1 with fixed files, and someone else said it worked, so try this.
https://drive.google.com/file/d/0BxSmknffFGTnTFJWeU1qQTl4TEE/view?usp=sharing

**Comment by northstar77** [comment]
@RobbieTechie Can you please do that for the Mac version? Thanks a ton!
