### ISSUE TITLE
It appears v2 API is shut down

### ISSUE THREAD

**Issue by RobbieTechie** [tomlandia/fuckr#105]
I'm hoping I'm wrong, but it appears that they shut that down last night/this morning.  Many more people are having a 400 (Bad Request) error.  If you put https://primus.grindr.com/2.0/services in your browser it gives a {"code":1002} which would happen when they forced the major update.  You also get a 400 when the app attempts to get a session.  I am hoping I am wrong, but it appears v2 has been laid to rest.

I have been working with v3, and had it somewhat working, but to make profiles show in the template I had to switch back to the v2 api code.  It pulled data for v3, but would not display.  I also tried changing the template as it pulled the data in profiles and not nearbyProfiles, but that did not work, but the app itself was getting the json data for the profiles.  I can also verify the map was working when I had the profiles showing up, and the markers on the map worked.  I messed with it last night and had some filters working too, but now testing with the api2 bit in there put this on hold

**Comment by stefanomartels** [comment]
I got a "suspended profile" message -_-

**Comment by kusaa** [comment]
Yes, it looks like the V2 API has been shut down.

**Comment by RobbieTechie** [comment]
I guess we're gonna have to figure out getting v3 api working.  I've made some progress, but I've got some spots I haven't.  I can get it to log in just fine, and it pulls profile data, but it does not display it.  I'm not sure if I'm having a data binding issue or just overlooking something very simple :/

**Comment by kusaa** [comment]
Sounds like you could be pretty close @RobbieTechie. Do you have this on the api-v3 branch or on a separate fork?

**Comment by RobbieTechie** [comment]
@kusaa 
I am working with the api3 branch.  If you simply download it though, it still uses the Fuckr folder the AppData directory so you either have to clear that out, or change it to use a different directory, which was what I did.  It will log in, but won't display anything.  Yesterday when I did have it displaying, using the api2, it doesn't act like it knows that it's logged in, as the top menu didn't show the settings and chat buttons, which appear after it verifies you are logged in.  

The api3 gets a session, gets your profileId, reads who you've blocked and who blocked you, then pulls the profiles.  It does not get the managed fields, which are part of the profiles, and it does not get undelivered chat messages yet.  And to get it to pull the profiles I hd to change a setting in fuckr.js
It origanlly said 
$http.get(API_URL + "locations/" + geohash + "/profiles/online=true").then(function(response) {
I had to remove the online=true part, as that caused a 404 error
$http.get(API_URL + "locations/" + geohash + "/profiles").then(function(response) {
After that, no more 404 and it pulls the profile data.

The filters setup needs to be changed, but one thing at a time.  With the v2 branch, you could just hit the profiles table at the top without being logged in, and it owuld display some profiles, which is what I'm first shooting for.  Perhaps @tomlandia is working on this, but I have no idea, so I'm going to see if I can at least make some progress.
