### ISSUE TITLE
Unexpected Error when Trying to Upload images

### ISSUE THREAD

**Issue by dvinan** [tomlandia/fuckr#110]
The app is working fine for the most part. I was testing the new version and I got an unexpected error (HTTP 413) when trying to upload images. Is it an issue for anyone else?

**Comment by gil2abir** [comment]
Also get here when trying to upload images to send in chat, or when uploading image to profile edit section.

**Comment by mark-chat** [comment]
I get this too.
Windows 10 64 bit

After failing to upload an image, the chat applet stops working.
I can browse profiles but no chat text box comes up when clicking chat

**Comment by RobbieTechie** [comment]
The 413 means the file is to large, meaning you need to resize the photo.

**Comment by dvinan** [comment]
Hey man thanks! i reduced the size and it worked out well
