### ISSUE TITLE
Ban

### ISSUE THREAD

**Issue by aurorainbowrealis** [tomlandia/fuckr#122]
Apparently Grindr is banning every account that is not accessed from a real phone. All tries that I made using Bluestacks, KOPlayer or Fuckr creates an account that is banned less than 3 seconds after the login. Anyone has the same issue?

**Comment by bootyliciousgeek** [comment]
out of so many tries i managed to create one. further attempts were futile. good news is i wasn't banned when i edited the profile in fuckr

**Comment by RobbieTechie** [comment]
No problems here.  If you're using a version from when we were fixing this, one thing I figured out was, if the height was less than 4 feet, you would instantly get banned.  I think that was how they countered all the 2'3' bots.

Other than that, the only problem I've ran into was once in a while the map would not work, and said the daily limit had been reached.  That was fixed by simply getting an api key.

**Comment by victorgrego** [comment]
Well Try to create a new account and see how it goes. Any acc that i create from fuckr client gets instantly banned. Same for android emulators. Although when i access any new account with the client it works perfectly.

**Comment by RobbieTechie** [comment]
I just created one using Fuckr and it works fine,  I edited the profile a little bit, and switched it from Metric to US and back and it's still going.  I'm wondering if maybe they do blocks by IP possibly, and perhaps since you're near school, maybe they had issues with people in the area and banned certain IP addresses maybe?

**Comment by victorgrego** [comment]
Did you use an authentic email address or just an nonexistent one?

**Comment by RobbieTechie** [comment]
non existant, I just randomly made a name and domain

**Comment by victorgrego** [comment]
Yeah, I just tried that and I get instantly banned, idk why.

**Comment by RobbieTechie** [comment]
Have you tried getting a different IP address.  If you change your network mac address you can get one that way, if you are dynamically assigned IP addresses, you might have to power cycle your modem and router if you get one cpe address, but it's worth a shot.

**Comment by RobbieTechie** [comment]
If you guys are using an emulator, you can try downloading an older version of the grindr, perhaps the new versions have "bad" code in them.  I know they keep putting crap in there and not telling people what they've updated.  Here is v3.0.12, https://drive.google.com/open?id=0BxSmknffFGTneVJ0aTRlNVF2U1E

**Comment by guynwpg** [comment]
Just logged into the same account I've been using since Robbie's latest build (like a good month now?) with no issues.

**Comment by Alastor1** [comment]
how do you know if ur banned?...cos i had 3 accounts, due to not being able to log in so i had to create a new one and so and so.....today the 403 error poped out again....so, im banned or is something else?

**Comment by RobbieTechie** [comment]
Grindr has been updating code on their server to prevent the use of any xtra features unless you are actually subscribed to xtra.  It will give an error 71, "filter could not be applied"  I don't know if that is banning profiles or not.  Mine seemed to lock up, then I logged into the actual app with the account and it was fine, so I went back to using Fuckr and it was all good, just had to keep the xtra features off.

**Comment by victorgrego** [comment]
I dont know, All my accounts have been banned. Like looks like grindr hates me now. even my beta tested have been removed.

**Comment by RobbieTechie** [comment]
I'm sorry man, grindr seems to be overly pissy about things lately, which is sad because their app isn't getting any and their entire system continues to go down hill.  You could likely test the theory about the ip address tied to the problem by using your phone as a hotspot or tether and see if that alleviates the problem, just a thought.

**Comment by Alastor1** [comment]
ohh I see, welp, I dont have android/ios at my hand so....I guess rip grindr for me XD plus bluestacks and andy sucks in my PC, hopefully sometime soon I will be able to use Fuckr again.

**Comment by RobbieTechie** [comment]
I'm not sure what the deal is exactly with all the actions of the app.  I did update the version on my fork last week to match the current one tomlandia is using, and added more profile data and filter options to that one.  I just tested it again, and was able to create an account and use it just fine.  The only thing I would be careful of, if you close then reopen it too fast, it will act like it won't log in.

**Comment by Alastor1** [comment]
ohh i see, how do i use ur....amm files, cos i downloaded them but....where do i put em?

**Comment by RobbieTechie** [comment]
On mine the 401 and 403 are errors for the xtra features, checking the online box is an xtra feature too.  If you have ANY of the xtra features active, it will throw a fit.  The only filters you can use for free are the age, looking for, and grindr tribes.  The 401 means unauthorized, and when that occurs, you need to exit out of the app for a few seconds then load it back up.

To use the files off my branch, simply extract the files into a folder, then copy them to where you have your files for fuckr, and overwrite any files it asks you to overwrite, then launch the app again.  If it throws a fit, you may need to clear the AppData folder again, but hopefully not.

**Comment by Alastor1** [comment]
Oh i didnt hace the issue before , the online thingy, welp . I tried ur files, I unzip em, i see 2 folders and 8 files and I cut them all and paste em in my fuck folder....but its doesnt load after that, i guess i did it wrong XD or should i only copy the content of your fuckr folder?

Thank you man!

**Comment by yanikucho** [comment]
Same, that's exactly what i did as well, and nothing happens when i try to
run it. And i had deleted my fuckr appdata first... strange

2017-04-03 1:22 GMT-04:00 Alastor1 <notifications@github.com>:

**Comment by Alastor1** [comment]
Oh indeed we re doing smth wrong haha @yanikucho , and whats this appdata erasing thing? where is that folder so i can erase it?....if thats of any help

**Comment by yanikucho** [comment]
before merging fuckr.me and robbie's pack, i had been suggested to erase
the fuckr file in %appdata% in the search bar (user`>loca, etc..) but still
not worked after that. we'll have to wait and see...

2017-04-03 16:59 GMT-04:00 Alastor1 <notifications@github.com>:

**Comment by RobbieTechie** [comment]
The app itself is separate from the AppData folder.  The AppData folder holds your chats, login data among other bits of info.  On Windows if you go to `c:\Users\%username%\AppData\Local\Fuckr` copy and paste that into your run or search on your menu, it will open, and you will see a folder called User Data, click on that, then press shift + del (hold down shift and press delete) to erase that folder.  You will lose your chats, and you will need to login again, but if there were any conflicts from an old version, this should help fix that problem.  You will also need to uncheck the online and photo only boxes, as those will prevent anything from showing up.

**Comment by Alastor1** [comment]
Ohhh i seee, hope it works thank you :D @RobbieTechie @yanikucho

**Comment by bootyliciousgeek** [comment]
so i have robbie's version, and the alpha 64 bit version. i can't create any new profile except when i downloaded them the first time. they also have different folders thingy, so i see different messages on robbie's and the alpha 64.
Then i downloaded the alpha 32 bit version and managed to create a new profile. This version however shares the same folder as robbie's version so i see the same messages. I then deleted the alpha 32 bit version.
This part i'm not sure how it happened, but from robbie's version I'm accessing the new profile. When i tried to log out and use the old profile, I got the 403 error. That old profile is still working though, and I can access it from another device.
How can i make them interchangeable?

**Comment by Kav28** [comment]
what I did was rename the folder for each profile name and run two versions
of fuckr

**Comment by Kav28** [comment]
need a change in the code too reflecting the name change

**Comment by RobbieTechie** [comment]
@bootyliciousgeek The current version on fuckr.me does not technically log you out, it will remove only part of what it needs to, to officially log you out.  You could clear the app data folder for fuckr, but that will erase chats.

 The folder name for storing data is controlled in a file called package.json in the main directory of fuckr.  Mine originally pointed to a folder called Fuckrtestbed instead of just Fuckr.
`"name": "Fuckrtestbed",`
if you change that to just
`"name": "Fuckr",`
that is how the current release is set

**Comment by bootyliciousgeek** [comment]
@RobbieTechie yeah it seems that as long as package.json points to a folder, fuckr will persistently show the last connected profile that used the folder. So there's no way to just transfer the messages or log out completely huh?

**Comment by RobbieTechie** [comment]
@bootyliciousgeek  The package.json file sets the folder is uses to store data.  It's going to be in your AppData\whateverthenameis normally it's Fuckr, but you could change the name to Fuckr2 or 2ndprofile and it would create a new directory, without erasing the old one.

You could transfer the chat messages, but I don't have the time to go into it right now, but yes it is very possible.

**Comment by bootyliciousgeek** [comment]
@RobbieTechie yeah i get that. i wanted to access the 1st profile whose messages are in the folder, but i somehow got a 2nd profile to use the same folder and now i can't log out and get the 1st one back unless i changed the json or deleted everything.

strangely i tried the win32 version, logged out, logged in to my 1st profile, and then use the win64 version and voila i'm logged in to my 1st profile again.

**Comment by Kav28** [comment]
can clone the fuckr folder, modify the json file to use fuckr_prof2 (orig
fuckr  folder json file uses fuckr_prof1) and then switch between the
profiles by just choosing which one to start.

should be able to change the code to augment the name of the file in the
json file with the profile name but so far I havent been able to do it
