### ISSUE TITLE
updated app/added filters, curious about more profiles

### ISSUE THREAD

**Issue by RobbieTechie** [tomlandia/fuckr#127]
I downloaded the latest version from fuckr.me then added back the filters for: looking for, tribe, ethnicity, body type, relationship, and position, hiv status is not a filter in the actual app.  I also fixed the online checkbox to function properly as the value changed from 'onlineOnly' to 'online'

I have also added the ethnicity, body type, tribe, relationship, looking for, and hiv status to the profiles.  The tribe will only show up currently if only one is selected, and looking for shows up as numbers, as I didn't process the numbers in the array into the word values.  If you would like to use any of the updates and incorporate them @tomlandia feel free to grab the code off my fork.

I've also tested this on windows 10 and it's working great.  I am using  a fresh install of Windows 10 and Fuckr, with Windows 10 updated with all updates.  I'm not having any issues of any kind.

Now I'm curious about making more profiles show up.  I customized a separate version of the app to download the rules and user prefs to view the differences between a regular account and an xtra version.   I need to switch OSs and will put the diffs up here, perhaps this will help to get more profiles to load.
![grindr](https://cloud.githubusercontent.com/assets/23042713/24330722/d75a5036-11f2-11e7-8ebc-7f6471edd555.jpg)

**Comment by RobbieTechie** [comment]
XTRA-Rules
---------------------------------------------------
app.maxPhotosAtOnce: 5
app.sendSavedPhrases.enabled: true
app.xtraSubscription.secondsRemaining: [redacted]
app.xtraSubscription.subscriptionId: "Grindr Xtra 1 Month Subscription Android"
broadcastsToDisplay: 3
cascade.maxPages: 1
cascade.profileQuantityPerPage: 600
eligibleForVideoAdRewardsOffer: false
isEligibleForVideoAdRewardsOffer: false
maxBlocksPerDay: [redacted]
maxFavoritesPerDay: [redacted]
serverTime: [redacted]
user.eligibleForFreeTrial: true
user.userRole: "Xtra"

----------------------------------------------------
Free-Rules
app.maxPhotosAtOnce: 1
app.sendSavedPhrases.enabled: false
app.xtraSubscription.secondsRemaining: 0
app.xtraSubscription.subscriptionId: null
broadcastsToDisplay: 3
cascade.maxPages: 1
cascade.profileQuantityPerPage: 100
eligibleForVideoAdRewardsOffer: true
isEligibleForVideoAdRewardsOffer: true
maxBlocksPerDay: 10
maxFavoritesPerDay: 10
serverTime: [redacted]
user.eligibleForFreeTrial: true
user.userRole: "Free"

**Comment by yanikucho** [comment]
@robbie: where can I download the pack you are using? i don't know anything
about code, but thx to all for all the great work!

2017-03-26 6:37 GMT-04:00 RobbieTechie <notifications@github.com>:

**Comment by RobbieTechie** [comment]
go here https://github.com/RobbieTechie/fuckr and click the button that says "clone or download" and download the zip.  Then extract it, and copy the files to your current fuckr folder, and overwrite anything it asks to overwrite, and launch the app again, and it should be good to go.

**Comment by GitHubGuy89** [comment]
Tried downloading and copying over the Windows version from main fuckr website. Then copied/replaced the RobbieTechie files, but still won't let me login, or signup for new account either. Gives no reason, just resets the name/password fields to blank. When I try to add a Date of Birth and different email, then click Sign Up, it just gives me the spinning "wait" symbol.

**Comment by misterhello** [comment]
@RobbieTechie Can you explain how to "overwrite" / install your version on a Mac? Thanks in advance!
