### ISSUE TITLE
Any way to get unlimited blocks back and more profiles displaying like Pro Version? 

### ISSUE THREAD

**Issue by powline99** [tomlandia/fuckr#129]
Any way to get the unlimited blocks back and more profiles displaying like there was in Fuckr before V3.0 update. I often run out of blocks now only to see the profile appear again. Is this a in app added feature constraint for pro vs. free or a server constraint. 

Thanks for all your work @tomlandia @RobbieTechie  

Enjoy the Having the Filters Back. 

For Anyone having issues using @RobbieTechie 's Fork 
Goto your Users folder in windows and local then app data and delete Fuckr. Install the newest release of Tom's Fuckr. I could not do the master zip file from Robbies Fork so I saw which files were updated within 2 days and updated only those and to tops Fuckr install and it worked.

**Comment by victorgrego** [comment]
Its impossible by now. The things are limited on server side.
