### ISSUE TITLE
No pictures/profiles returned after login

### ISSUE THREAD

**Issue by Kav28** [tomlandia/fuckr#13]
This evening behavior changed - login seems to go through normally but no pictures are setup in the left side pane. sign out behaves normally but same thing happens when I sign in again. Earlier I tried to upload a new profile pic and the upload just spun. Prob happened subsequently.

Dennis

**Comment by tomlandia** [comment]
Do you have the latest version (Jan 2)? I tried logging in and out and changing pic and all seems to work.

**Comment by victorgrego** [comment]
Grindr servers seems a bit unstable recently, I think it may be de issue. Both information retrieving and packet loss was happening often.

**Comment by Kav28** [comment]
This was the latest version. I also tried the earlier versions with the
same results.  This morning it was working again but still couldnt upload a
profile pic - kept spinning. Will try again with the earlier versions.

Thx - Dennis

**Comment by victorgrego** [comment]
which platform are you using Fuckr on. I just tested it here and photo upload was ok.

**Comment by Kav28** [comment]
Windows 10 64bit.  Am trying it from other laptops. 

On Jan 9, 2016, at 11:48 AM, Victor Nascimento <notifications@github.com> wrote:

which platform are you using Fuckr on. I just tested it here and photo upload was ok.
