### ISSUE TITLE
Unable to filter

### ISSUE THREAD

**Issue by nwiaguy3** [tomlandia/fuckr#14]
Perhaps it's because of my screen resolution (1366x768), but I am unable to find anywhere to change the filter on the windows version of fuckr.  Currently, it is only showing profiles with photos, and I would like see all profiles.

**Comment by nwiaguy3** [comment]
I was able to modify profiles.html to add a check box to change photoOnly to false.  Not sure if it's worth including in a future realease.

**Comment by jwax33** [comment]
I would appreciate that feature, actually!

**Comment by tomlandia** [comment]
Added in v1.5 (just released).
