### ISSUE TITLE
Expired Tokens and Having to Relogin often on Fuckr

### ISSUE THREAD

**Issue by powline99** [tomlandia/fuckr#142]
@tomlandia @RobbieTechie

Robbie or Tom, thanks for all your work, you make Grindr use able. Can you fix the issue with the expired token, mine (win 7 - 32 bit) disconnects every few minutes, I cannot just let the program stay on. Makes using Fuckr hard. Running the newest update. Robbie Talks about this below. 

[(RobbieTechie commented on Apr 1
When Fuckr stops being able to chat, that means that the tokens have expired for the sessions. This happens on Windows too. There is a section in the API documentation where it talks about refreshing and getting a subsequent token, which I believe would solve this problem, rather than processing the login again.

I have not bothered with that yet, as I've been lazy myself and not made an attempt at fixing that. I'm sure @tomlandia could take care of that very quickly. Currently the app uses the login processing to get session tokens, which is why, when you close the app all the way, then reopen it, it will allow you to chat again. I think changing it from popping up the XMPP error, and just having the app post the authToken, email, and token specifically to https://grindr.mobi/v3/sessions would resolve the chat disconnects. I might make some attempts to see if that works later today if I have the time. I'm not a professional coder, so working with this app has been a great way to learn.]

**Comment by powline99** [comment]
Hi Robbie @RobbieTechie was this fixed in your recent fork?

Thanks!

**Comment by RobbieTechie** [comment]
Nope, I just added the filters back so far for that.  I haven't much looked into refreshing the token lately as I have not been using Fuckr much lately and grindr not really at all
