### ISSUE TITLE
Selecting More Than One Selection in a Filter At Same Time @RobbieTechie

### ISSUE THREAD

**Issue by powline99** [tomlandia/fuckr#144]
@RobbieTechie Is there any way of selecting more than one filter at a time. Ie. Ethnicity, in the app you can select a few choices at once, tribes, etc.

Thank you for your work on the Fork!

**Comment by RobbieTechie** [comment]
If you mean selecting say a tribe and what someone is looking for at the same time, yes.  If you mean something like looking for jock and clean-cut at the same time, (same category) no.  The free version of the app doesn't even let you do that, if you try to select more than one, it spams you to upgrade

**Comment by RobbieTechie** [comment]
No
