### ISSUE TITLE
11 kB GCM token in account creation vs. 16 digits XXXXXXXXXXXXX.XXX token for session creation

### ISSUE THREAD

**Issue by JKalash** [tomlandia/fuckr#149]
I have noticed the following while sniffing traffic from the iOS app. 

On account creation, a huge 11 kB token is sent to the app. Does not look like a GCM token to me. Nothing gets anywhere near such size (~ 10k chars). Session creation is a mere 16 digits and a period that changes periodically. These observations are not consistent with the "unofficial" documentation. Anyone knows how to generate these tokens to create an account?

**Comment by RobbieTechie** [comment]
There is no need to bother with for this for Fuckr, as it already creates an account just fine.

**Comment by RobbieTechie** [comment]
Is there a point to this? Fuckr works just fine...

**Comment by JKalash** [comment]
@RobbieTechie Sure there is. Trying to implement account creation and getting bad token resp. What is the format of the output token used in `chrome.instanceid.getToken` ?

**Comment by RobbieTechie** [comment]
My point was, why are you bothering to do something that has already been done and is working fine.  I just created an account with no problems what so ever using Fuckr and it works just fine.

**Comment by JKalash** [comment]
Because i'm working on recreating a similar app on a different platform and am trying to get a sense of how the token validation works and how tokens generated by GCM in chrome extension vs Android / iOS sdk differ in terms of validity to Grindr

**Comment by JKalash** [comment]
Nevermind. After much checking, turns out the simple instanceId.getToken does not have an equivalent for iOS. GCM library for iOS forces an APNS token to be sent which would return a token that fails validation.
