### ISSUE TITLE
Fuck+

### ISSUE THREAD

**Issue by victorgrego** [tomlandia/fuckr#152]
So, I came for the hype. Yesterday we got a question asking whether or not would it be possible to use Grindr as an Xtra user. After answering a clear "no", two good mugs of coffee and messing up my sleep...

![image](https://user-images.githubusercontent.com/6922949/27395347-be21a632-566c-11e7-8d01-64276728b945.png)

I call it Fuckr+ [Since Xtra is taken hahaha]. 
P.S. Yes, I do change the UI for my personal version.
@RobbieTechie if you could please, I would like your help testing this before releasing :)

**Comment by RobbieTechie** [comment]
As far as I'm aware, you can sign up for Xtra using the actual app, then just log in with that same account and you will get all the xtra features to work, all filters, 600 guys on grid.  That seems controlled on the back end and the set of rules applied.

I looked at your repositories for this and didn't see Fuckr up there, so how do I get it if I may so boldly ask =D

**Comment by victorgrego** [comment]
Hmm, I am actually planning a closed beta before i actually release this, as there is some bugs.
And no, I am not paying for Xtra to do this :)
mail me: durzobur[at]mihep[dot]com

**Comment by RobbieTechie** [comment]
email sent

**Comment by victorgrego** [comment]
I've sent you the files and some insight on the process. Feel free to play.

**Comment by RobbieTechie** [comment]
I didn't get anything yet, not sure if gmail is stubborn about tempmail, so I guess use kekkocitro@mihep.com to message me back

**Comment by leakydata** [comment]
Oh wow!  Could I get a copy too?  :)
leakydata@gmail.com

**Comment by RobbieTechie** [comment]
I got the email, but no links or files

**Comment by victorgrego** [comment]
lel gimme ya skype

**Comment by RobbieTechie** [comment]
I actually don't have a webcam hooked to my pc lol,  I just sent a message from gmail again

**Comment by RobbieTechie** [comment]
Success!!

**Comment by victorgrego** [comment]
You can always talk to me in san francisco ;)

**Comment by mratmsf** [comment]
would love a copy as well ;)
mratmsf@gmail.com

**Comment by victorgrego** [comment]
We are not distributing it just yet because it has many issues, we will update our branches when the time comes. Thanks.

**Comment by JKalash** [comment]
Thank you!

**Comment by JKalash** [comment]
All I'm saying is, and it's only theory pending validation/rejection: there are obvious security measures where a user can spoof the dns table of the iOS or somehow have a fake "app store" validate a receipt for grindr subscription. If that happens and there is not backend check for receipt validation then somehow the client needs to perform a POST request telling the backend the user just upgraded his membership. If that's the case then what is that API? And would calling it automatically activate xtra for any newly created account?
