### ISSUE TITLE
Token fix/update

### ISSUE THREAD

**Issue by RobbieTechie** [tomlandia/fuckr#174]
@tomlandia  I've been collaborating with @Mitsj0l and @victorgrego and we found a solution for the token, mostly Mitsj0l figured it out. We're not sure how big of an issue it would be to implement it, would you be able to help if given the info?  If so please respond or email me [REDACTED]  then the info can either be posted or emailed which ever you prefer.

**Comment by Mitsj0l** [comment]
It seems that though Google gives a Token initially with this code in Fuckr (see below), the generated token is being marked invalid by Grindr:

authentication = function($localStorage, $http, $rootScope, $q, $location, $timeout, API_URL) {
  var getGCMToken, useCredentials;
  getGCMToken = function() {
    return $q(function(resolve, reject) {
      if ($localStorage.gcmToken) {
        return resolve($localStorage.gcmToken);
      } else {
        return chrome.instanceID.getToken({
          authorizedEntity: "1036042917246",
          scope: "gcm",

Underwater in this same POST call, the Chromium part will add the following part:
     --data-urlencode "app=<generated by the Chrome Extension>" \
However, when we change the app to com.grindrapp.android and add the field 'cert: "ce1f7e703ccca26d2c4ef3e48fd5ae0ea4cb1c29"', we have a winner token which allows Fuckr (manually for now via static tokens) to login/register new accounts.

This means that we would need to change the API to retreive a GCM token: https://developer.chrome.com/apps/instanceID#method-getToken function.. As of now, it seems that the only attributes we can add are the scope + sender (1036042917246). We can add 'options' to the request,  but attributes like app will be appended in by X-, so it becomes X-app. And that doesn't generate a working token..

I can think of two solutions for this problem:
1. Finding a way how to edit the request as suggested above.
2. Retrieve the aidlogin part that is being generated by the function chrome.instanceID.getToken, and code a api call ourselves with the right attributes.

In regards to number 2... When we take a look at the Chromium engine, this is the code that will build the content that is being used for the Authorization (Aidlogin <DeviceID>:<SecurityToken>: https://github.com/ChromiumWebApps/chromium/blob/master/google_apis/gcm/engine/registration_request.cc

Being specific, I believe this is the part that will retrieve the deviceID && securitytoken:
  std::string android_id = base::Uint64ToString(request_info_.android_id);
  std::string auth_header =
      std::string(net::HttpRequestHeaders::kAuthorization) + ": " +
      kLoginHeader + " " + android_id + ":" +
      base::Uint64ToString(request_info_.security_token);
  url_fetcher_->SetExtraRequestHeaders(auth_header);

If, we would be able to retrieve the mentioned attribites, we don't need to leverage the closed source API of Google to get a Firebase GCM token. 

Which leaves me to the question, how van we retrieve the deviceID && securitytoken?

**Comment by RobbieTechie** [comment]
Because of the large amount of emails I'm getting from other people that I didn't ask to contact me from this issue I'm not going to be giving out tokens.  Fuckr is being worked on, and if it gets fixed, it will work, if it doesn't then I am probably taking a break.

I've also had someone asking for details, and acting like they are @tomlandia but saying they want info and would be "happy to mess around with it and return my findings".  That doesn't appear to be @tomlandia to me, but if it is, I apologize for being rude.

The numerous repeat requests for tokens from the same few certain individuals, and I'm talking like 8-10 times they want a new token, has become ridiculous, and then multiple emails from certain people under different addresses wanting multiple tokens to mess with this just doesn't cut it either.  As I've said, if we get it fixed, the tokens won't be an issue.  If it does not get fixed, I may work on it privately to implement things that were said to be planned for this release such as the different look, and if it gets fixed, at a later date those things will be updated to take the current version of Fuckr out of an Alpha release.

**Comment by victorgrego** [comment]
Robbie, I don't know if you still follow this, but the file you sent me with the request does not work. I figured out how to fix the key problem, but I can't make the correct request. mail me if u still active.

**Comment by RobbieTechie** [comment]
Sorry Victor, I've been crazy busy for a bit, but I'll email you later today

**Comment by ZeroFeetAway** [comment]
They're no longer using GCM tokens. No request is being made in order to obtain this token. The app is generating it from within and then it is being verified by the server in some way.

**Comment by victorgrego** [comment]
@zerofeetaway they actually are.

**Comment by ZeroFeetAway** [comment]
@victorgrego I don't see any requests, at least within the iOS app to google as far as a GCM token though? Maybe they're using GCM for just android?

**Comment by victorgrego** [comment]
@zerofeetaway maybe yeah. Fuckr uses android style so we use gcm for auth, and it is known that they are using gcm. The current working version uses gcm to auth.

**Comment by Grindr13** [comment]
Fuckr is no longer usable #157  

> Closes #174

**Comment by powline99** [comment]
@RobbieTechie @victorgrego @Mitsj0l  Was there any fix to the token thing. My fuckr on Windows Disconnects every 2 mins, I have to log out and back in again for it to function. Error Message "XMPP chat error. If your're using public wifi, XMPP protocol is probably blocked." 

Any fix so I can just leave it running. I updated to Robbie's newest update from the End of December 2017 unless there is some other update I am not aware of. Let me know if I can provide you any other information. Thank you for all your work!
