### ISSUE TITLE
l^

### ISSUE THREAD

**Issue by Mb94800** [tomlandia/fuckr#178]
Hey,

**Comment by Grindr13** [comment]
Fuckr doesn't work at all and it hasn't since July 6, 2017. #157 

> Closes #178

**Comment by RobbieTechie** [comment]
This is not an actual zip file, I just changed the extension to upload it here, just remove the .zip part and copy it into your main Fuckr setup.
[package.json.zip](https://github.com/tomlandia/fuckr/files/1713983/package.json.zip)

**Comment by loco222** [comment]
@RobbieTechie 
Now the error is: Your profile can not be used because it is from a newer version of NW.js.

Some features may be unavailable. Please specify a different profile directory or use a newer version of NW.js.
