### ISSUE TITLE
Token Error That Disconnects or Something Else - Have to Force Quit Process and Restart Every 1 or 2 Mins?

### ISSUE THREAD

**Issue by powline99** [tomlandia/fuckr#181]
@RobbieTechie @victorgrego @Mitsj0l  @shyrat @tomlandia 

Can anyone tell me if this is a Token Error or Something Else. Fuckr Disconnects every 1 or 2 minutes and have to Force Quit Process and Restart. Also tried log out and log back in. Any Fix for this?

* Running Windows
* No other Grindr app instances Running While on Fuckr
* Newest Version of App from Main Github Fuckr Repository and tried Installing Robbie's Jason package.
* Error: "XMPP chat error. If your're using public wifi, XMPP protocol is probably blocked."
* Also Error: "Grindr servers temporarily unavailible (HTTP 504)"

I remember Tom before did a fix for this that kept it running for a long time, then Grindr updated and @RobbieTechie did a great fix... has something changed again with a new update? 

Let me know if I can test in any ways... Tell me what to look at in Chrome for the Errors and I can paste if you need. 

@RobbieTechie Any chance you will do a project of your own with a fork now that it seems Tom abandoned Fuckr. 

Much Appreciated!

**Comment by RobbieTechie** [comment]
The version I have currently will fix most of the filters, I think one is still blank, and it will allow you to log in, but not create a new account.  It also will reload the app when the token problem comes up.  Just a note, it reloads the whole app.  I have to put it together and zip it up, then upload it, then I will share it here.

**Comment by RobbieTechie** [comment]
The auto refresh is suppose to be every 7 minutes be default, the problem could be the version of Node Webkit, or it could be something that Grindr changed on their servers.  I may release my version, it won't allow account creation, but it would allow logins and when it gets errors it reloads the app.

**Comment by powline99** [comment]
@RobbieTechie IF It's node webkit, do we just download and replace this or would it have to be coded for the new webkit. That would be great for your to release whatever you could. Thank you!

**Comment by RobbieTechie** [comment]
The first thing to check would be to make sure you're not running the same account on your phone or tablet and fuckr at the same time.  I did that the other day and it kept closing
