### ISSUE TITLE
Filter's Broken Profile.html, Drop Down Selection: Ethnicity, Position, Tribe, Status,etc.

### ISSUE THREAD

**Issue by powline99** [tomlandia/fuckr#182]
@RobbieTechie @victorgrego @shyrat  @genevera @zachdrago Anyone who can help.

Trying to figure out how to fix profile.html for the Filters.
I paid for a month of Xtra thinking it would make the filters work in fuckr (as they are grayed out on the real grindr) :-(

Drop down for ethnicity, position, etc... I see them when I pull in the views folder profile.html into Chrome (all the drop downs are there). But They are not showing up on Fuckr. Was this broken somehow in the most recent update by @RobbieTechie

![capture525sd](https://user-images.githubusercontent.com/16879733/36839747-c7a63d56-1cf7-11e8-843c-60fd2bd8721a.JPG)

<div class="pure-u-1-2 scroll">
  
  <div class="pure-g">
    <form class="pure-form">
      <fieldset>
        In
        <input ng-model="$storage.location.name" class="pure-input-1-3 pure-input-rounded" id="location" type="text" placeholder="Location">
        Between
        <input class="small-input" ng-model="$storage.filters.ageMinimum" ng-change="refresh()" min="18" max="99" size="2" type="number">
        And
        <input ng-model="$storage.filters.ageMaximum" ng-change="refresh()"
               class="small-input" min="18" max="99" size="2" type="number">
      </fieldset>
      <fieldset>
        Online
        <input type="checkbox" ng-model="$storage.filters.onlineOnly" ng-change="refresh()">
        Photo only
        <input type="checkbox" ng-model="$storage.filters.photoOnly" ng-change="refresh()">
        View as
        <select ng-model='view' ng-change=refresh()>
          <option value="thumbnails">Thumbnails</option>
          <option value="map" selected>Map</option>
        </select>
      </fieldset>
      <fieldset id="managed-fields" ng-if="managedFields">
        <select ng-model='$storage.filter.lookingFor' ng-options="option.fieldId as option.name for option in managedFields.lookingFor" ng-change="changeFilter('lookingFor')">
          <option value="">Looking For Any</option>
        </select>
        <select ng-model='$storage.filter.grindrTribe' ng-options="option.fieldId as option.name for option in managedFields.grindrTribes" ng-change="changeFilter('grindrTribe')">
          <option value="">Any Grindr Tribe</option>
        </select>
        <select ng-model='$storage.filter.ethnicity' ng-options="option.fieldId as option.name for option in managedFields.ethnicity" ng-change="changeFilter('ethnicity')">
          <option value="">Any Ethnicity</option>
        </select>
        <select ng-model='$storage.filter.bodyType' ng-options="option.fieldId as option.name for option in managedFields.bodyType" ng-change="changeFilter('bodyType')">
          <option value="">Any Body Type</option>
        </select>
      </fieldset>
    </form>
  </div>

  <div class="pure-g" >
    
    <a ng-if="view == 'thumbnails'" ng-repeat="profile in nearbyProfiles" style="position:relative;" class="pure-u-1-5" ng-click="open(profile.profileId)">
      <img class="pure-img thumbnail" non-draggable
           ng-src="http://cdns.grindr.com/images/thumb/320x320/{{profile.profileImageMediaHash}}"/>
		  <div class="caption textoverlay">{{profile.displayName}}</div>				
    </a>

    
    <ng-map ng-if="view == 'map'" center="[{{$storage.location.lat}},{{$storage.location.lon}}]" zoom="10" id='map'>
      <marker ng-repeat="(id, location) in locations"
              position="[{{location.lat}},{{location.lon}}]"
              id="{{id}}"
              on-click="markerClicked($event)">
      </marker>
    </ng-map>
  </div>
</div>

<div class="pure-u-1-2 scroll">
  <div id="profile" ng-show="profile" emoji>
    <img class="pure-img" id="profile-pic"
         high-res-src="http://cdns.grindr.com/images/profile/1024x1024/{{profile.profileImageMediaHash}}"
         ng-src="http://cdns.grindr.com/images/thumb/320x320/{{profile.profileImageMediaHash}}"/>
    <h2 id="displayName"}>{{profile.displayName}}</h2>
    <h3 id="headline">{{profile.headline}}</h3>

    <p>{{profile.aboutMe}}</p>

    <p class="icons" ng-show="profile.socialNetworks">
      <a ng-repeat="(name, info) in profile.socialNetworks" target="_blank" href="https://{{name}}.com/{{info.userId}}/">
        <i class="fa fa-{{name}}"></i>
      </a>
    </p>

    <p ng-show="profile.lookingFor && profile.lookingFor.indexOf(7) != -1" style="color: red">Looking for Right Now</p>

    <p>{{profile.seen | lastTimeActive}}</p>

    <table ng-show="profile.height || profile.weight || profile.age || profile.sexualPosition" class="pure-table">
      <thead>
        <tr>
          <th>Age</th>
          <th>Height</th>
          <th>Weight</th>
          <th>Position</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>{{profile.age}}</td>
          <td>{{profile.height | cmToLocalUnit}}</td>
          <td>{{profile.weight | gramToLocalUnit}}</td>
          <td>{{sexualPositions[profile.sexualPosition]}}
        </tr>
      </tbody>
    </table>

    <p ng-show="profile.distance">
      <b> {{profile.distance | mToLocalUnit}} away</b>
      <i ng-show="isNearbyProfile(profile.profileId) && (!pinpointing)" class="fa fa-globe fa-2x" ng-click="pinpoint(profile.profileId)"></i>
      <img ng-show="pinpointing" src="img/spin.gif">
    </p>

    <p ng-show="authenticated" class="icons">
      <a non-draggable ng-href="#/chat/{{profile.profileId}}">
        <i class="fa fa-comments fa-4x"></i>
      </a>
      <a ng-click="block()">
        <i class="fa fa-ban fa-4x"></i>
      </a>
    </p>
  </div>
</div>

**Comment by genevera** [comment]
@powline99 try the [g_main|https://github.com/genevera/fuckr/tree/g_main] branch of my fork for that.

**Comment by powline99** [comment]
@genevera  Thank You for responding! I could not make it work, see the attached screen grab. Replaced the views folder and the css filters. Is it something else from your main branch?
Thank You!
![capture456564565](https://user-images.githubusercontent.com/16879733/36877235-041f3168-1d6e-11e8-93cf-bf522a117f3a.JPG)

**Comment by RobbieTechie** [comment]
Grindr removed the managed fields from their server and hard coded them into the app itself.  As for the online and photo only in the profiles.html, on approximately line 16, in the last version released here, it said
`<input type="checkbox" ng-model="$storage.filters.onlineOnly" ng-change="refresh()">`
You need to change that online only to just online, remove the Only part
`<input type="checkbox" ng-model="$storage.filters.online" ng-change="refresh()">`

**Comment by powline99** [comment]
@RobbieTechie Thank You for your kind help. I tried replacing as instructed to the above but still get the weird empty filter boxes the same as the above (see picture). Could it be the code is broken somehow. I see the filters w/ drop down when I pull in profiles.html to Chrome, but not in Fuckr, ... perhaps it's being cut off or something, I tried it on the main distribution version as well (this shows no drop downs - perhaps it's cutting them off). The above was @genevera profiles.html version. IT's weird they are showing up in the profiles.html when I pull into chrome but not in the app itself. Could be as you stated managed fields or something. Thank you for your dedication, I can't wait for your version of fuckr to be posted to zip.
Thanks!

**Comment by genevera** [comment]
Hmm.  I must have done some massaging of the application data locally because it def works for me (at least tribe, looking for, and age).  I feel like this app probably needs to be completely redone from the ground up.  I'm terrible at UI but would be happy to assist on anything else.

**Comment by powline99** [comment]
@genevera Thank you, you know so much more than me. Is there any way I can get a copy of your fuckr as it seems to be functioning (zip - can provide you a email if you wish). I am on Win 10 64bit. I can't seem to figure out the filter part. The filers show up in chrome when I drag in profile.html for Robbie's recent update from Dec 2017 but they do not show up in the Fuckr program. I then tried yours and as you can see above ^ from the pics, they are cut off (the drop down's have no data in the fields). Any ideas? I don't know what to do anymore. Also any idea how to get it from disconnecting every 2-5 mins, this must be some hidden error in Chrome. I am on Wifi. Have to use TaskKill.

I want to humbly thank you for your generosity and help.
P.

**Comment by aurorainbowrealis** [comment]
@powline99 it is currently not possible [as far as we know] to get filtered data. What we had in the past was that we could pass some parameters and the server would return the filtered data, that is not the case anymore. 
Another side problem is that when you get the nearby profiles the server does not return the full profile, but rather a short version. Therefore, if you want to filter what you would do is collect all those profiles that are nearby and filter locally, as @genevera suggested. However, to do that you would do around 200 calls to the grindr api in less than a second, so BEWARE, you could be banned. 
If someone else has a better way to do this, please let me know.

**Comment by RobbieTechie** [comment]
@powline99 here is the version with filters back in.

I had to add the filters back in, so when you're using your xtra account, if one of them does not work, please let me know.
https://drive.google.com/open?id=1IfZT4D2m1Cb86AcupOtacYWdD_hBTEMy

**Comment by Kav28** [comment]
am using an extra account but cannot type in location box. Can type in the
age range box. No pics/profiles show up in the grid.

**Comment by RobbieTechie** [comment]
This happened before when we were switching from version 2 to version 3.  Press F12, or right-click and then select Inspect from the menu.  Across the top menus, go to Application, then on the left side of the menu double click on Local Storage, then click on chrome-extension:// and you will see the data storage with the key:data pairs.

 Click on ngStorage-location to highlight it.  Then on the right side, under value, double click so the value for ngStorage-location is highlighted, and then delete it.  Now you should be able to type in the location bar and set a location.

**Comment by Kav28** [comment]
worked - Thx

**Comment by RobbieTechie** [comment]
Glad to hear that, you're welcome
