### ISSUE TITLE
When pictures are sent from fuckr, the receiver in grindr app can't open the thumbnails.

### ISSUE THREAD

**Issue by xfy741** [tomlandia/fuckr#186]
People can see the thumbnail preview but the picture is not shown when they click on it. Grindr has changed their image gallery from picasso-cache to bumptech/glide since version 3.22.0. I am not sure if this has something to do, I don't know about programming but I hope you can find out this.

**Comment by victorgrego** [comment]
For me just re-uploading the pics I wanna send fixed that problem. If you had pics for a long time in yr profile they will not even send the thumbnail

**Comment by xfy741** [comment]
In the chat database the picture sent with fucker appears as:

{"imageHash":"xxx..."}

but with the grindr app:

{"tapType":0,"imageType":0,"imageHash":"xxx..."}

**Comment by victorgrego** [comment]
okay, so does that break Fuckr?

**Comment by RobbieTechie** [comment]
At this point, this appears to be version dependent, I have an older version of Grindr on my phone, and sending pics from Fuckr to that version works fine.  However I have 3.21.2 on my tablet, and sending to that does not load the photos.

I have verified that in both cases the photos that are sent through chat are accessible in a browser, but the Grindr client won't load photos from old versions of grindr

**Comment by RobbieTechie** [comment]
I think I've figured more of this out.  Taps are a bit different, but with images, they changed the data tied with them.  The old versions were
{"imageHash":"fbc986acd6303db12bfdfa4bd163563f021b1ff0"}
The new versions
{"imageHash":"ced5ed50dfa67fa40ed4b1b18c5ec71b82a36852","imageType":0,"tapType":0}
That 2nd one is not a tap, yet they attach the tap type to it.  Regular typas just look like
{"tapType":1,"imageType":2,"imageHash":"taps/hot.png"}

**Comment by RobbieTechie** [comment]
And specific to  the app itself we have:

```
package com.grindrapp.android.model.factory;

import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import com.grindrapp.android.GrindrApplication;
import com.grindrapp.android.activity.ChatActivity;
import com.grindrapp.android.view.transformers.imagebody.ImageBodyTransformer;
import javax.inject.Inject;
import o.ApplicationInfo;
import o.NotificationActivity;
import o.Response;
import o.Session;
import o.fv.If;
import o.gn;
import o.gp;
import o.gt;
import o.gu;
import o.gv;

public abstract class ChatTypeAbstractFactory
{
  @Inject
  public ApplicationInfo grindrData;
  public final Session val$s;
  protected JsonObject val$ssub;
  
  protected ChatTypeAbstractFactory(Session paramSession, JsonObject paramJsonObject)
  {
    val$s = paramSession;
    val$ssub = paramJsonObject;
    GrindrApplication.get().inject(this);
  }
  
  public static ChatTypeAbstractFactory doInBackground(Session paramSession)
  {
    Object localObject = Response.id;
    String str = key;
    if (((Enum)localObject).name().equalsIgnoreCase(str)) {
      return (ChatTypeAbstractFactory)new gt(paramSession, new JsonParser().parse(type).getAsJsonObject());
    }
    if (Response.equals(key))
    {
      localObject = new JsonParser().parse(type).getAsJsonObject();
      if ((((JsonObject)localObject).has("imageType")) && (((JsonObject)localObject).get("imageType").getAsInt() == fv.If.title.ordinal()))
      {
        if (((JsonObject)localObject).has("advertiser")) {
          return (ChatTypeAbstractFactory)new gn(paramSession, (JsonObject)localObject);
        }
        return (ChatTypeAbstractFactory)new gp(paramSession, (JsonObject)localObject);
      }
      return (ChatTypeAbstractFactory)new gv(paramSession, (JsonObject)localObject);
    }
    return (ChatTypeAbstractFactory)new gu(paramSession);
  }
  
  public abstract Runnable access$getMFinishLoadAndSortTask(ChatActivity paramChatActivity);
  
  public abstract ImageBodyTransformer intValue();
}
```

**Comment by RobbieTechie** [comment]
We also have this:

```
package o;

import com.google.gson.annotations.SerializedName;

public class Pair
{
  @SerializedName("tapType")
  public int count;
  @SerializedName("imageType")
  public int id;
  @SerializedName("imageHash")
  public String name;
  
  public Pair() {}
  
  public Pair(Level paramLevel)
  {
    id = author.ordinal();
    count = count;
    name = name;
  }
}
```

**Comment by RobbieTechie** [comment]
This is fixed and will be updated shortly

**Comment by RobbieTechie** [comment]
Fixed image sending and cleaned up a bit of the html, this also has filters back in it.  This WILL NOT create an account but it will allow you to log in and function.  If anyone has issues please let me know.  @xfy741, if this works for you, please close this issue as I will post this on the main issues section.

https://drive.google.com/open?id=1IfZT4D2m1Cb86AcupOtacYWdD_hBTEMy

**Comment by xfy741** [comment]
@RobbieTechie It works!!! Thankyou for your work, you are a brilliant guy! That's why I said grindr changed the image gallery from picasso to glide and I mentioned about the tap thing in the database but you are the programmers. The ones who can make those changes in code.  I am just an end user.

**Comment by RobbieTechie** [comment]
It wasn't actually the change from picasso that mattered, but you mentioning the database did help me track down the change, so good work!!

**Comment by silesia12** [comment]
@RobbieTechie : HI, please can i ask u for the fixed fuckr? I try it, but its doesnt work for me. I already send in google drive request access. Many thanks ,-))

**Comment by fiveparmak** [comment]
@RobbieTechie I have the same problem at grindr. The pics that I take are just text and also the pictures that I sent goes in the same way. CAN you just help me to fix it. I sent also Google drive request. Many thanks.

**Comment by RobbieTechie** [comment]
Sorry guys, I didn't realize you posted here since this was closed.  If you edit the file fuckr.js, and look for the line
`imageHash: imageHash`
which is around line 330 give or take, it's under the function to send images, and change it to 
`imageHash: imageHash , imageType: 0`
save and reload the app, the sending of images should work properly

**Comment by RobbieTechie** [comment]
@silesia12 @fiveparmak 
Sorry guys, I didn't realize you posted here since this was closed.  If you edit the file fuckr.js, and look for the line
`imageHash: imageHash`
which is around line 330 give or take, it's under the function to send images, and change it to 
`imageHash: imageHash , imageType: 0`
save and reload the app, the sending of images should work properly

**Comment by fiveparmak** [comment]
@RobbieTechie thanknyounfor explanation, d does it work when I am taking same error at my smart phone application. Also it seems you didnt five permission for Google drive. Can younolease give me permission to reach file.
