### ISSUE TITLE
New Fuckr release, cleaned up html, added some profile data, sending pics works again

### ISSUE THREAD

**Issue by RobbieTechie** [tomlandia/fuckr#187]
This is on Google Drive, it may say it can't preview, it did that to me, but it will still allow you to download.  Just unzip this to what ever fold you wnat and it will work.  You may also overwrite your old fuckr files or folder.
Just a note, THIS WILL NOT ALLOW YOU TO CREATE A NEW ACCOUNT, ONLY LOG IN.

[redacted]

**Comment by xfy741** [comment]
@RobbieTechie Great Job! Thanks a lot! I couldn't open it the first time, but then I erased the userdata in the /appdata/fuckr folder and everything went fine, the thumbnails are opening and I really like the filters and the html change when the profile picture is not found. Thank you again!!

**Comment by RobbieTechie** [comment]
You're welcome

**Comment by powline99** [comment]
Thank You!!!! @RobbieTechie 

Feedback:
On Windows 10 64bit - Xtra Account
Had to delete prior Fuckr version and user/_/appdata as it was looping restarts once I installed the new version.
1) Filter work -yay
2) Like Improved Profile Info - yay
3) Any way to favorite (star)? 
4) Constant auto-restarting of app (White flash), every time I block, when I send a message, even when browsing profiles. Can be annoying mid convo. Any way to turn this function off or background it with the app open so you don't loose your place or what your doing. Don't recall this in the past though the prior error messages were annoying from Grindr's servers. Maybe I had a pieced together version. 
5) Has the bitmining code been removed that was discovered?
6) It makes 4 instances of the "nwjs" for memory ussage 17.4MB, 60.9MB, 58.3MB, 1.4MB
7) Will Add More Edits when I discover / think of more...

THANK YOU, can't wait for your project in the future - Good Vibes Sent!

**Comment by RobbieTechie** [comment]
I may add the ability to favorite users, I have a version I've tested and can do it manually so I know it's possible, just haven't worked at coding things into the app yet.

With the blocking, sometimes it restarts and sometimes it doesn't, for me anyway.  Same with the profile block or chat.  I'll have to dig more to figure that out, it may just be something with the way the app functions.

As for restarting by itself, I set the app up to restart when disconnected from xmpp, so it will reconnect to chat, otherwise the chat box disappears and the error pops up.  That is another area that needs looked into.

No bitmining.

The multiple instances has to do with the way chrome runs, the chrome browser runs in a similar way and node webkit is basically the chrome browser that's modified by the people that wrote NW.

I'm glad it's working better, I'll see what I can do about some of these other issues soon.
Also some of this I have to give credit to Victor for some of the ideas, he was the one that came of with the reload to fix the chat, a while ago, we both just deal with it and it hasn't been fixed like the actual app yet.

I'm actually looking at making a new version of this, but I've got more learning to do first with a newer version of Angular.

**Comment by powline99** [comment]
@RobbieTechie Could we implement something like this in the future for Fuckr. Could be useful information. Scared to give away access to my account to some rando site. Seems to be info available on the back end of the server. 

https://www.reddit.com/r/askgaybros/comments/857i0w/cckblocked_see_whos_blocked_you_on_grindr/

https://blocked.ongrindr.com/

Cheers

**Comment by xfy741** [comment]
This xposed app is very useful, please chek it @RobbieTechie 
https://forum.xda-developers.com/xposed/modules/mod-t3373222

**Comment by RobbieTechie** [comment]
@powline99 There are ways to see who you've blocked and who blocks you, I can verify that.  I'm not sure I trust that site.  I'll make an account and test it and report back here.

@xfy741 I've seen that before, you need a rooted device for xposed, some are easy to root, some are not.  For the most part those things could be done in Fuckr, as for the bit about unsending chats, that seems a bit ify to me, but maybe they do have it working.

**Comment by RobbieTechie** [comment]
@powline99 that site does work, but it appears to also store your data, so I tested it then deleted the account I tested with.  I don't recommend using it with anything other than a test account.

**Comment by xfy741** [comment]
@RobbieTechie I don't use it on my phone, there are emulators working with grindr, those are Koplayer, MeMu and Nox. I think Nox is better but MeMu is the only one with Lollipop.  @RobbieTechie I have a question, is it hard to create an app for viewing the pictures and the chat database stored in the grindr cache in the same way you see it in the grindr chat tab. Some people just want to save a chat with the pictures they already have on their phones, fuckr just work for the new ones. It could be like a log viewer or something. I can see the database with a sqlite viewer but is not organized by user, it is sort by timestamp and no pictures, just hashes. I would really like an app like this: Grindr history viewer and saver.

**Comment by RobbieTechie** [comment]
I'm aware of the emulators, they're good in some areas and not so good in others.

As for an app, I believe they are using an sqlite3 database for grindr.  If you wrote an app to view the data you could really control how it is sorted, by profileId or timestamp etc.

Those hashes you see are the pictures, thats how they name the images.  In theory no two images are the same so no two hashes would be the same.  I know grindr in the past had talked about being able to back up your chat history, which would require exporting the database or portions of it, and for what every reason they never bothered.  That is one of the biggest downfalls of that app.  If you switch to a new device, you lose the convos.  Personally I have no plans to develop something like that at this time as it doesn't seem there is much of a demand for it.

**Comment by xfy741** [comment]
@RobbieTechie if you use Titanium Backup, you can create a backup and everything is restored,app and data.

**Comment by fm2000** [comment]
@RobbieTechie ... thanks for this - im assuming this can only be used for windows?

on mac, i duplicated the fuckr.app holder, and copied all those new folders into the package .. and get this when i open it up 

> 
> Your profile can not be used because it is from a newer version of NW.js.
> 
> Some features may be unavailable. Please specify a different profile directory or use a newer version of NW.js.

surprisingly it then open and SEEMS ok ... but once logged in, just shows the fields as blanks:

Age | Height | Weight | Position
-- | -- | -- | --
{{profile.age}} | {{profile.height \| cmToLocalUnit}} | {{profile.weight \| gramToLocalUnit}} | {{sexualPositions[profile.sexualPosition]}}

any ideas?

**Comment by fm2000** [comment]
ps ... @RobbieTechie - and just one other qn, for newer accounts, how do i find out what the authtoken should be? thanks to you ive been able to kind of get the old build working on mac with accounts that i already had run previously, but any new ones it seems to get stuck on not having the ngstorage-authtoken value ... any tips much appreciated

**Comment by RobbieTechie** [comment]
@xfy741 I don't even bother with backup, when I use it on a rooted device I just copy the databases and bingo, back up.

@fm2000 When the profile data show sup like that, it usually is referencing a filter programmed in that isn't there.  You would need to copy the package.json in the root folder, then copy the fuckr.js from the root folder, and then copy the / views folder to update the profile views, then most likely it should go.  You still won't be able to create accounts but you can still log in.

**Comment by powline99** [comment]
@RobbieTechie FYI... 
https://www.pinknews.co.uk/2018/03/19/what-is-cckblocked-the-app-that-reveals-who-blocked-you-on-grindr/

**Comment by RobbieTechie** [comment]
Part of that concerns me, as it saves the authToken, which is basically your password hashed out, that is how, after you log in, you don't type your password any longer.  The authToken is saved on your device as the password to your account.

**Comment by baleguise** [comment]
Anyone else having trouble with tokens here?
Tried downloading, deleting all the cached user data, etc. but can't get it to log in.

When I run it through Fiddler I get an invalid token error - and don't know how to fix it!

**Comment by RobbieTechie** [comment]
I just ran it with the version I last put together, cleared all my data and logged in again just fine

**Comment by waddup1001** [comment]
@RobbieTechie Thank you for this update. Mac user this side. I managed to log back in and even found some of my old chats from 1 year back. If I go back to my old chats, I can still see the profiles of the people I was chatting too.
However, I'm unable to select a location  and can't see profile thumbnails on the main grid? Any idea what might be wrong?

**Comment by waddup1001** [comment]
@RobbieTechie Thanks for the update! Mac user this side! Once I copy-pasted all the folders in the app.nw root folder, I was able to log back in. Strangely, even though I was using a new account, I found my old chats from 1 year back from a different email ID I was using then.

However, in the main grid, I still can't select a location or see the profile thumbnails. Any idea what might be wrong?

**Comment by Grindr15** [comment]
@RobbieTechie Can you create an account on Grindr on your phone and then login to Fuckr or do you have to already have an account that was used with Fuckr to get this to work?

**Comment by RobbieTechie** [comment]
@ghost Currently with what was released, you should be able to use an already existing account, or create a new one using the app and either should work.  This isn't set up for Mac yet though.  I am looking into using Transmac, but if one of you mac users can get the files from the windows version and replace it in the mac setup, that should work.

@waddup1001 The chat data is stored right on the computer, so as long as you are using the same folder for data storage the chats will remain.  If you can't set a location, that may prevent it.  If you have the developer version, on Windows you hit F12 and you can inspect, I'm not sure what it would be on Mac.  You can also right-click up by where the fuckr logo is and see if it pops up a menu where you can select inspect, then you'd have to look accross the top for "Application", then on the left side fo the screen look for "Local Storage" and then crhome-extention and the data is under there, try clicking once on "ngStorage-location" so the key and value are both highlighted and hit delete, then you should be able to enter a location.

**Comment by silesia12** [comment]
Hi everybody, I have some small problem. Can not enter location, doesnt work. I get online , but without location. Somebody can help? Many thanks

**Comment by gev22** [comment]
@RobbieTechie 
any chance for a unix (ubuntu) working version?
Thanks

**Comment by powline99** [comment]
@RobbieTechie  They are using Fuckr In this article, look at the pic

https://securityaffairs.co/wordpress/70851/hacking/grindr-gay-dating-app-issues.html

**Comment by RobbieTechie** [comment]
What they don't understand is that that is a normal function of the app, all that guy did was read the array of users that blocked someone and someone was blocked by, which is downloaded every time the app gets launched.  That site was nothing special in all reality.  Grindr has certain functions that it performs when someone logs in, and the block list is one of those functions.

**Comment by powline99** [comment]
@RobbieTechie Any way to fix the reloading every time I block, I have to block some people 2 and 3 times. Xtra Subscriber. I try clicking log-in and letting it automatically login. It crashes and reloads every time. Even sometimes just clicking on profiles and browsing, then you wait for it a few seconds to load up again. Win 10 - 64bit. Wifi connection. Is the Grindr server delaying the connection or something. They recently did some work on the app/server (Android version is shit), ... this now takes 10 seconds to block someone (Wonder if they are delaying it) to avoid server time or something and clicking on profiles is slower.
Thank You!

**Comment by powline99** [comment]
@RobbieTechie  http://www.breitbart.com/tech/2018/04/02/report-grindr-sharing-hiv-statuses-of-users-with-third-parties/

**Comment by Kav28** [comment]
I know a lot of guys who do not reveal their true status (+ or -) on
grindr. whoever is buying the info is naive

**Comment by Kav28** [comment]
I find that android app is better than iOS app. Android seems to do a
refresh at some time interval. on iOS you have the same refresh but it also
seems to happen when some action is performed (a block, favorite). Fuckr
just seems to have the periodic restarts for refresh. In fuckr it seems
that the map is more accurate than the reported distance.

**Comment by powline99** [comment]
@Kav28 Do you know how to backup on Andorid past chats - Grindr. I tried a few apps on a test account and it didn't transfer over my past chats. I want to downgrade the APK and see if it's faster than their current build. The support said they know there is a huge issue with the current build being slower to block, load profiles off the grid, and a new feature to change the Icon (from the Grindr standard one to incognito - it basically deletes the app from Android).

Thanks!

**Comment by Kav28** [comment]
I use fuckr on windows, grindr on multiple iOS devices and multiple android
devices. I find that once I start the app on a device, pending
conversations get downloaded to the device and they are no longer available
for other devices - the conversations dont sync. when the app gets upgraded
the conversations that are on that device get into the upgrade but nothing
on other devices.  fuckr does seem to keep these in a file so it seems that
it should be possible to merge the fuckr/conversations on one laptop into a
second by merging these files. I havent tried merging them but have xfr the
file, brought up a new fuckr and they were present.

**Comment by RobbieTechie** [comment]
In a nutshell, grindr has been lying to users about their location accuracy and data mining. It's overly fucking accurate, I can see which room in a house I'm in.  I've know gps enabled apps that can also track which level of a building your in, perhaps on their back end they can do that.  The app also appears to be set to track a user.

@powline99  if your device is rooted, you can copy the databases folder, it sometimes throws a fit, and sometimes you have to clear the cache but not the data in the app to get it to go when putting it back, but if you clear it, you can copy it back in.  Really that's all they'd have to do to back up chats, I've done this at different times. 

@Kav28 The chats are stored locally in an sqlite database, which is why they are only local, grindr has never given you the direct ability to back them up and restore them.  On fuckr, the chats don't get removed, unless you clear the data folder, and you can copy the chat data out easily and replace it.  If you used the old versions of Fuckr, when you logged out, and used another account, ALL your chats would still remain, even though you logged in as another users.  The last Fuckr @tomlandia released never finished never finished the actual logout function, but that would still be the same if you actually logged out.

**Comment by fm2000** [comment]
sorry ive taken so long to log bacm and reply but have been on the road ... but just thanks for the advice Robbie.

**Comment by RobbieTechie** [comment]
It's all good, people get busy, you're welcome and I hope you had safe travels.

**Comment by pete9090** [comment]
Can someone mirror the download link which has been removed? Looking for mac version.
