### ISSUE TITLE
My latest Build Works to anyone who wants

### ISSUE THREAD

**Issue by CanadianJeff** [tomlandia/fuckr#188]
https://github.com/CanadianJeff/fuckr

in the package.json file the USER-AGENT needs to match the current build of the app itself or it gets blocked

**Comment by RobbieTechie** [comment]
That's cool that you indirectly forked that from me, but that shouldn't be the case that it gets blocked if it's not the current build.  There are other issues present in this as well, but since you claim this is your latest build, I'll let you figure that out.

**Comment by CanadianJeff** [comment]
no need to get hostile its the idea of open source to fork from people

**Comment by CanadianJeff** [comment]
and honestly IDC what you say or think it works for me so I am gonna keep it

**Comment by RobbieTechie** [comment]
You go right ahead, I just thought you mike like to know it still has problems
