### ISSUE TITLE
View as Map not working for some locations

### ISSUE THREAD

**Issue by mehranZAMAN** [tomlandia/fuckr#193]
The ''View As Map'' feature is not working for some cities whereas for other cities it is working just fine. 

Here are 3 screenshots : Lahore (not working), Mumbai (working), Dhaka (not working)
NOTE : Windows 10. Has no previous version of Fuckr installed. Everything else works fine.

![1](https://user-images.githubusercontent.com/33387342/39397968-3df8e954-4b29-11e8-9556-26d03c97f45a.PNG)
![2](https://user-images.githubusercontent.com/33387342/39397969-3e3b4c36-4b29-11e8-9a26-290abb5c74a0.PNG)
![3](https://user-images.githubusercontent.com/33387342/39397970-3e7a05a2-4b29-11e8-95fd-6a5f633393cc.PNG)

**Comment by RobbieTechie** [comment]
The app works just fine, it's Grindr that is the reason you see no users pinpointed there.  They use "geofencing" to block distance in certain countries and certain regions, typically where it's not legal to be gay or where there is a potential threat to the people of that region.  This is normal opporation and not a problem with the app, so if you could, please scroll to the bottom and close this issue, thanks

**Comment by mehranZAMAN** [comment]
Sure. Thanks
