### ISSUE TITLE
People without an age don't show up

### ISSUE THREAD

**Issue by bobbygold** [tomlandia/fuckr#20]
There are some profiles that don't have ages tied to them, typically it is users that use Grindr on an apple phone.  I'm not sure if this is a glitch, but I know a few of them around me, and they are online but do not show up on the grid or the map.  I looked at the SQLite database and there is no age value even present under the age section of these certain profiles so I think the program automatically won't show them up because the value for age is missing.  If you need me to screen shot the database please let me know.  I did notice if you are not logged in to the Fuckr app they will show up,

While logged in I had one of them message me, and it still won't map them out even when clicking on their profile from the messages.

**Comment by tomlandia** [comment]
This app does display profiles without an age value even if you specify filters (I guess for those who have showAge: false). Just in case, and for cleanness, I cleaned up the filter parameters in 351210e.

**Comment by tomlandia** [comment]
The map only works for profiles showing distance and that are relatively close btw
