### ISSUE TITLE
Remember password option

### ISSUE THREAD

**Issue by strumpet123** [tomlandia/fuckr#22]
The app logs out once in a while (not sure if it's a bug), but could you have a check box to remember password for easy re-login?

**Comment by tomlandia** [comment]
This feature was removed when Grindr implemented Captcha's and Fuckr had to use an iFrame.

**Comment by strumpet123** [comment]
Ah, do you know why it logs out by itself?

**Comment by tomlandia** [comment]
Implemented 'remember password' by hacking a little bit. Will be released this week.

Right now Fuckr handles 401's by forgetting the auth token (useful if you log in with another device) but I've changed that in 0f31051 as it's probably unnecessary if session has only times out.
