### ISSUE TITLE
app fails with Error 1001 on DNS resolution

### ISSUE THREAD

**Issue by Kav28** [tomlandia/fuckr#3]
This morning the app failed to start - instead of the login screen I get an Error 1001 on DNS resolution for account.grindr.com referencing cloudfare, Gives a long hex string as the cloudfare ray id.

Thx - Kav

**Comment by mister-g** [comment]
+1 Same problem as Kav28 - error 1001.

**Comment by mister-g** [comment]
(I use os x version)
anyway thanks for this great app and for the response ;)

**Comment by Kav28** [comment]
Found it fuckr partially starts: if you click on the rightmost icon the pics for the guys show up but no profile information.

**Comment by tomlandia** [comment]
Thanks for reporting!

http://account.grindr.com moved to http://neo-account.grindr.com/ so the fix is trivial but I'll only release it tomorrow with other changes. Sorry about the delay.

**Comment by Kav28** [comment]
Thx for the app. Helped me learn about writing pc clients for mobile devices.

**Comment by bobbygold** [comment]
Fixing this login error was easy go to the \fuckr\views folder and edit the source of the login.html file, then find:
 <iframe src="https://account.grindr.com/login">
change to:
<iframe src="https://neo-account.grindr.com/login">
as the author states above, they changed the accounts.grindr.com to neo-accounts.grindr.com

I do have a few questions on this program.  It appears that you can block people an unlimited amount of times, is that correct?  Also, is there an option to favorite people?, I didn't see that anywhere, but wasn't sure if I missed something.  And lastly, when you sign in, is your distance off by default, i have not had a chance to dig through the folders to look for any settings for such things.

I'm guessing this bypasses the rules in the android app
/data/data/com.grindrapp.android/shared_prefs/Rules.xml which controls the amount of favorites, blocks, time left on extra and basic filters and settings.
I was also curious if there was a way to modify the html in fuckr, to allow these settings for searches and what not.

**Comment by FreddieG** [comment]
I'm still having isses with connecting after changing the login adress, when i type in my email, password and captcha, it just stays there doing nothing after i click LOG IN...
Hopefully you can help me, since it's an awesome app and i'm really really looking forward to using it.
Pizza & Beers are in it for you if the geography gods are kind :)

**Comment by Kav28** [comment]
Made the change, no DNS error but I get a pop up window saying I need a new app from the google store.

**Comment by bobbygold** [comment]
Sorry guys, I forgot I changed a couple other files.  I used a program called Ultra Edit, to open them all and search for **account.grindr.com** and changed them to the **neo-account.grindr.com**

I changed these files along with the webpage
**authenticate.coffee**

**Comment by crowleyhick** [comment]
When will the new code be up to download?

**Comment by FreddieG** [comment]
It still doesn´t work for me after making the changes. I think it's because when i extract the file from the compressed folder, it says it didn´t extract some of them because their locations were too long

**Comment by Kav28** [comment]
Made the changes and everything seems to work. Thanks

**Comment by bobbygold** [comment]
@FreddieG  If the locations are too long, try just making a folder under say  c:\fuckr and extract the files there, then make the changes and it should work then.
@Kav28  You're welcome, happy fuckring lol

**Comment by tomlandia** [comment]
Sorry about the delay :(, I've finally released v 1.2. Thanks a lot for reporting and for the temp fix!
