### ISSUE TITLE
Running locally

### ISSUE THREAD

**Issue by AlbertPWilliams** [tomlandia/fuckr#30]
Hi all,
Hoping someone can help.
To get the latest version, I tried to run the app from the code.
Following the run instructions here:
https://github.com/tomlandia/fuckr

cd fuckr/
nw .

The nw . isn't recognised.
I assume this is:
nodewebkit .
That gave a window 
![capture](https://cloud.githubusercontent.com/assets/6164926/13849254/354fc3f0-ec4d-11e5-9a83-7aee57c26a67.PNG)

Looked at the code & googled for help..but had no joy.
Any help please...thanks!!

Windows 7, 64bit OS

**Comment by tomlandia** [comment]
Probably an old Node-Webkit version, you'd need at least 0.12 to support HTTP requests handler that have become necessary since Grindr implemented Captchas
