### ISSUE TITLE
Getting authkey without the chrome.webrequest

### ISSUE THREAD

**Issue by victorgrego** [tomlandia/fuckr#31]
Anyone got an idea to substitute the chrome.webrequest? As far as I know, it isnt possible to track the 302 redirection, but its also not possible to get the URI.

**Comment by tomlandia** [comment]
Exactly I don’t see how you could do it with a normal browser because grind-account://* URLs raise errors too early. Doing it with a plain REST client would be ugly too because of the captcha (Fuckr used Node.js `request` before captchas).

**Comment by victorgrego** [comment]
Do you know any method, even manual, to obtain the auth key?

**Comment by tomlandia** [comment]
With either Firefox or Chrome, go to http://neo-account.grindr.com/login, open the dev console on network tab, log in and you should see a red POST request from which you can grab the `grindr-acount://` link with the auth token.

**Comment by victorgrego** [comment]
Thanks for your answer! I'm coding an alternative Grindr to mobile, so we could grindr like Xtra on the phones for free. I'm using Adobe Phonegap. Any help would be very appreciated! (https://github.com/victorgrego/Ashu)
Btw, i found a workaroud for mobile. The `grindr-acount://` is a redirect and can be used to call applications. So I just made my app to listen to this custom schema. Tricky huh!?
So you just need to open the browser and login and the app will open retrieving the information session :D

**Comment by tomlandia** [comment]
OK makes sense for a mobile app. Closing as it's not a Fuckr issue.
