### ISSUE TITLE
Location problem

### ISSUE THREAD

**Issue by obertscloud** [tomlandia/fuckr#32]
Today getting location problem,  I enter a city for example Berlin Germany, I am getting results in UK, and other Countries, but not Germany

**Comment by tomlandia** [comment]
Thanks a lot for reporting! Yes Grindr does return people from hundreds / thousands miles away with no apparent reason.

**Comment by obertscloud** [comment]
Your welcome but there are none from Wurzburg my tablet and phone app  receive Germany,  or Berlin where I set it,  but your app is having problems ?  I tried three computers today.


Date: Mon, 21 Mar 2016 21:27:14 -0700

**Comment by tomlandia** [comment]
It looks fixed now as for Berlin (without filter), the furthest profile (500th) is 130km away. It really looks like it was a Grindr server problem when you fetch 500 profiles from the server at a time like Fuckr.

**Comment by Kav28** [comment]
GrindR had a popup saying this was a problem today.

**Comment by tomlandia** [comment]
Closing but thanks again for reporting it fast 👍.
