### ISSUE TITLE
Stuck on main page no content loading

### ISSUE THREAD

**Issue by n997** [tomlandia/fuckr#37]
I'm running the app on a Macbook Air and it has not been running at all for around a week now, any idea what's wrong? @tomlandia
![screen shot 2016-03-31 at 14 20 41](https://cloud.githubusercontent.com/assets/18190918/14177000/f06e7826-f74b-11e5-8854-94640bcce505.png)

Thanks

**Comment by tomlandia** [comment]
Thanks. It's not easy to debug a packaged app but I'll soon release a version using nw 0.13 using my own nw-builder fork (it's an awful shame the official nw packager doesn't support the latest nw version 😡) so I'd love if you could test it then.

**Comment by n997** [comment]
@tomlandia sounds good!

**Comment by tomlandia** [comment]
Available on https://github.com/tomlandia/fuckr/releases/1.6.0 , please test!

**Comment by n997** [comment]
Thank you! @tomlandia

**Comment by n997** [comment]
@tomlandia Hey I was having the problem with not being able to login and the box going grey as well is there a link for the mac download of the 1.6.1 release? Thank you :)

**Comment by tomlandia** [comment]
It's there now. Github release bugs randomly with DMG's so I had had to upload it several times :/

**Comment by n997** [comment]
@tomlandia  thanks dude ;)
