### ISSUE TITLE
Not Sending Messages

### ISSUE THREAD

**Issue by victorgrego** [tomlandia/fuckr#38]
IDK if u finished the updates, but the release from fuckr.me does not reflect the last github push.
So i downloaded the github code and it is not sending any message when I press the send button or Enter. Using windows 10 64bits

**Comment by tomlandia** [comment]
Wow embarrassing 😅 thanks for reporting. Fixed in [v1.6.1](https://github.com/tomlandia/fuckr/releases/tag/1.6.1).
