### ISSUE TITLE
Cannot Login Newest Release

### ISSUE THREAD

**Issue by powline99** [tomlandia/fuckr#39]
@tomlandia 
I downloaded the newest release and I am stuck on the login screen, the login button grays out when I hit login and sits there.

**Comment by tomlandia** [comment]
Gotcha 😨 will fix in 8 hours as I'm at work 😛. Must be a Chrome Webrequest API problem with the new Node-Webkit version.

**Comment by powline99** [comment]
@tomlandia  Thank You

**Comment by tomlandia** [comment]
Fixed in [v1.6.1](https://github.com/tomlandia/fuckr/releases/tag/1.6.1), thanks again for reporting.
