### ISSUE TITLE
Title

### ISSUE THREAD

**Issue by victorgrego** [tomlandia/fuckr#4]
Can we have a title field on the profile view?
Ps. its crashing sometimes on windows x64

**Comment by victorgrego** [comment]
I've implemented the profile displayName and the displayname over the grid on hover.
http://pastebin.com/mYmz9MUk
http://pastebin.com/cMrrHav1

**Comment by tomlandia** [comment]
Merged #5 but I suppressed most CSS changes and translated JS changes to coffeescript
