### ISSUE TITLE
Chat doesn't work

### ISSUE THREAD

**Issue by gazkk** [tomlandia/fuckr#44]
Hi, the chat system doesn't work. I can send messages but don't receive any. Also the app crashes every couple of minutes and needs to be restarted. I'm on Mac (el Capitan), npm is installed. Any clues?

Update: I noticed I cannot be seen by others. Also it only appears I have sent my messages. When I tried with a friend he never received my messages.

**Comment by n997** [comment]
Also seem to be having this same issue

**Comment by victorgrego** [comment]
+1 to this.
Chat does not work AND my profile does not appear to others. I've logged on acc on phone and another in fuckr and the fuckr does not appear. It may be some authentication or missing info issue.

**Comment by gazkk** [comment]
Thanks for the response! I changed the lines according to the fix posted by @tomlandia in chatController.coffee and ran the build.sh in app.nw (coffee gave a warning about a deprecated command but seemed to work fine). 

Is there anything else I need to do? The chat and visibility functionality doesn't yet seem to work for me...

**Comment by tomlandia** [comment]
I've been looking at and it affects older versions and leaves zero debugging information so it will probably take some time to fix sorry.

**Comment by gazkk** [comment]
No need to be sorry -- thanks for all your work! I had a look myself but unfortunately this is all a bit new to me... Not sure I can be of any help but if there's anything a beginner can do, let me know.

**Comment by tomlandia** [comment]
Both points work fine right now with nw 0.12 or 0.15 so this will be fixed in v1.6.2 (v1.5.1 was temporarily on fuckr.me). It miiigght have been because of nw0.14's lowercase headers.
