### ISSUE TITLE
Map Feature Not working to See Location inside Profiles

### ISSUE THREAD

**Issue by powline99** [tomlandia/fuckr#45]
@tomlandia Map function not working when I click on world icon in profiles, it just spins and does nothing. Map does work if you use drop down view in main screen. Could this be my spam blocker in Chrome or setting not to open new windows, just tabs?

Thanks!

**Comment by Kav28** [comment]
Have had that prob but think it happens sporadically - might be due to
load.

**Comment by tomlandia** [comment]
V1.6.1 is a shitshow sorry. It's not the one on Fuckr.me. Going to release 1.6.2 using nw 0.12.1.
