### ISSUE TITLE
Chats Only Show up in Fuckr Software, Even After Logout, New Replies Don't Open in IOS Grindr??

### ISSUE THREAD

**Issue by powline99** [tomlandia/fuckr#46]
This one is a bit strange. I start chats while at my laptop on the same username as my IOS mobile. I know chats do not save across platforms but before I was able to start a convo and then go mobile and also have a new chat open up if the person responded. Now the responses only go to Fuckr even if the software is closed and I am fully mobile and logged in for a few hrs??? I wonder if this has to do with the phantom processes / sessions after crash issue I posted before, it still thinks I am logged in and so never truly closes software / logs out. I tried to manually log out same thing, but if a session is running after a crash and stuck in memory then I suppose it does nothing.

**Comment by Kav28** [comment]
If I start a chat with the most current version of Fuckr, sign out and then
start a older version of Fuckr replies to the chat will not come in until I
sign out and then start the new version of Fuckr. If I have two users (not
used at the same time) chat history of both users will be visible but new
messages will not appear until I am signed in as the user intended for the
chat (changed behavior from earlier versions).

**Comment by tomlandia** [comment]
I'm confused as if it's yet another weird v1.6.1 but going to implement XMPP disconnect just to make sure.

**Comment by genevera** [comment]
@tomlandia i think maybe it's confirmchatmessagesdelivered that deletes them from the server.  I've been experimenting with that locally and it seems to be the case.
