### ISSUE TITLE
Fuckr will not logout, stays in background processes after program closed or crashes

### ISSUE THREAD

**Issue by powline99** [tomlandia/fuckr#48]
@tomlandia Fuckr will not logout, it stays in the background processes after the program is closed or crashes (seems I am still on Grindr still). Multiple instances taking up resources. Have to do full shutdown to make them go away.

**Comment by tomlandia** [comment]
Yeah v1.6.1 is a shitshow sorry. It's not the one on Fuckr.me. Going to release 1.6.2 using nw 0.12.1.
