### ISSUE TITLE
v1.5.1

### ISSUE THREAD

**Issue by newtofuckr** [tomlandia/fuckr#50]
Hi I am new to this site (just joined a few minutes ago --- I only joined so I can comment on your program).

I first tried Fuckr a few months ago. 
Back when gay dot com was in their heyday, a master programmer created the "chat client" application, that allowed easy accessing the site, blocking a lot of the spam with a "botguard".

I have had problems though the past few weeks with messages on Fuckr--I can send, but I am not receiving any, and my profile is NOT showing online--which is another reason I am not getting messages..I had an older version of Fuckr (which had worked really well up to that point, so I decided to update to the 4/25/2016 version--and its not helped at all).

I read that closed discussion you have, and I tried to go in the "coffee" to change the lines you talked about, but there is no way to edit that file, I tried. I don't know a huge amount about programming. 

On the fuckr.me website of yours, it still lists v1.5.1 (the April 25 version) as the downloadable version (you said it was temporarily online, it's still listed as the default download for windows). Do you know when a newer version of Fuckr for windows will be able to be downloaded, or is there a link you can give me to download a newer update? As I am hoping that next version will allow my profile to be shown online Fuckr, as well as me getting messages again.

Most of Grindr's errors, are indeed with Grindr -- I have talked to many guys on Grindr that said they have problems with messaging all the time -- and most guys are actually using Grindr, and not Fuckr, no one I have chatted with on there has admitted to using Fuckr. 

I will be patient. As I do not have the expertise or training otherwise to "remedy" the version I currently have.  I am using other "social" websites in the meantime. 

Also a suggestion for a future version to have an "auto-updater" (unless that would be too difficult) -- chat client had an auto-download to update the software -- 

Thanks once again for making this program. I consider you a friend for all the effort and hard work you have put into it. :)

**Comment by powline99** [comment]
I believe he is releasing them here (below) until they are stable. It still is in sorta a Beta version right now, he is working to bring out 1.6.2. I believe there has been some changes at Grindr so hes adding features and fixing the issues. 

https://github.com/tomlandia/fuckr/releases

**Comment by tomlandia** [comment]
v1.7.0 has been released on is used on https://fuckr.me .
