### ISSUE TITLE
No support for multiple accounts at the same time

### ISSUE THREAD

**Issue by boes4** [tomlandia/fuckr#54]
The app is amazing, but I've had some problems with my profiles. When I've logged in into two profiles once on the same computer, they overlap in conversation. One account talks in a conversaton and all of a sudden it seems that my other account is talking to them Can that problem be fixed?

**Comment by tomlandia** [comment]
Yes due to XMPP use supporting multiple accounts on the same device would be non-trivial. On second thought, it'd also be quite shady so I'll tag it `wontfix`.
