### ISSUE TITLE
dangerous

### ISSUE THREAD

**Issue by Instrumedley** [tomlandia/fuckr#58]
Hi Thomas. I tested the app for the first time today and couldn't help realize that the app makes it available the EXACT location of users. Please, I urge you to fix this. This puts in danger many gays that live in countries where being gay is still an issue (such as Uganda, Russia, Iran, etc...)

**Comment by powline99** [comment]
@Instrumedley Fuckr does not do this, Grindr already allows you to do this with Triangulation. Many people have contacted Grindr about this issue and yet they keep it and don't fix it. There are a few apps actually that allow the same thing. They warned people in those countries not to use the app, the government already watches those who use it.

**Comment by Kav28** [comment]
They did make the change that the distance reported is rounded down to the
whole mile unless youre under 1mi in which case its the nearest ft.  So if
youre more than a mile away triangulation will give you 1sqmi area. Of
course if youre using bluestacks/grindr you can change your location,
triangulate to get the 1sqmi and then triangulate again to get the position
- with the error in the address/gps conversion.  Can also be done if the
distance is not given by the location subject by sandwiching bewteen those
who do give location but there is increased error. gpsvisulaizer.com has
some routines that can be used.

**Comment by tomlandia** [comment]
Yup no plan to do security through the front-end sorry; you can try to contact Grindr but I assume they won't listen 🙉.
