### ISSUE TITLE
can't login to Fuckr!!!

### ISSUE THREAD

**Issue by hotabz** [tomlandia/fuckr#60]
Can anyone help me as I can't even find a help or support section.
I'm logging in with my same info as I would on grindr and it keeps giving me a message of : use a valid email address.
Its valid!
then when I go and try to set up new account with that email, its says "already in use"

How the hell do I get onto this app???

**Comment by Kav28** [comment]
Sure you have the passwd correct?  Can try using the app to change the
passwd, waiting a day (in case it needs to propagate) and then sign in
using fuckr.

**Comment by tomlandia** [comment]
Works right now and you can even reset password in Fuckr's login page.
