### ISSUE TITLE
Can't change location?

### ISSUE THREAD

**Issue by sfxworks** [tomlandia/fuckr#62]
I have a bit of a setup.

Running on Raspbian on Raspberry Pi.
Pulled an ARM build of nw from hell (an hour or so of searching https://github.com/nwjs/nw.js/issues/1151#issuecomment-78030735)
Logged in, got it running.

I can load my profile/chat with users/upload images in Sanfransico, CA but no where else.  I tried putting in Charlotte, NC (my area) and hitting enter and it just clears the field. Then I try changing other things and it resets it or brings up images of people in that same location. I even tried tabbing away from it. The text will stay there, but the location wont update. 

Something I have to do besides enter to update my location? There a file where I can just set my gps?

The map wont load either.. I can get the UI for google maps, scroll bar and arrowas and all, but the map wont load.

Edit:
Tried changing controllers/profilesController.coffee to update my location. Same people appear. 

Also, I don't know if this has to do with the map that isn't working but it hit my terminal.
```
[ sent ] <a xmlns="urn:xmpp:sm:3" h="1"/>
[26242:0805/083311:INFO:CONSOLE(210)] ""Google Maps API warning: NoApiKeys https://developers.google.com/maps/documentation/javascript/error-messages#no-api-keys"", source: https://maps.googleapis.com/maps-api-v3/api/js/25/12/intl/en_gb/util.js (210)
```

**Comment by sfxworks** [comment]
> Install node-webkit **>= 0.13** (eg. npm install -g nodewebkit) and run nw fuckr

Oh
ok holdon

**Comment by sfxworks** [comment]
https://github.com/LeonardLaszlo/nw.js-armv7-binaries 

Which one is the right one to build and how do I build them? New to building and compiling. Coming form windows and a bit of knowledge from centos as far as webhosting goes.

**Comment by mark-chat** [comment]
On Windows, after typing the name / post (zip) code of the place you want to be located, you wait a second and a list of searched places arrives as a drop down menu for you to select one. 

You can't just type a place and hit return, you have to select an address from the drop down list that appears. Hope this helps....

**Comment by tomlandia** [comment]
Sorry about your build problem; Fuckr is stuck to NW.js 0.12.3 right now. Going to close this issue as changing location works fine right now.
