### ISSUE TITLE
Accounts created with new version cause insta-ban from grindr

### ISSUE THREAD

**Issue by GitHubGuy89** [tomlandia/fuckr#66]
Tested this out at least 3 different times, and each time resulted in a insta-ban.

1. Used fuckr to create a new account.
2. Once logged in, before doing anything else, I exited fuckr and started it up again. It let me in fine.
3. Tried to create a profile, added headline, age, weight, etc... (Regular stuff, nothing spam or anything)
4. Exited fuckr and started it up again. 
5. Got the unexpected error and couldn't log in anymore. Account was banned.

Appears you must create the account you want to use and setup the profile on an actual mobile device. Will be trying that out next and see if it lets me log on/off fine from fuckr.

In the meantime, I'd be wary using any "personal/main" accounts right now.

Windows x64 version

**Comment by tomlandia** [comment]
Closing due to APIv2 shutdown.
