### ISSUE TITLE
Resource killer

### ISSUE THREAD

**Issue by gayallday** [tomlandia/fuckr#67]
This new 1.7.0 version of FuckR really hammers my core i5 2.6ghz processor on my HP g6 laptop.  The last version hardly moved the cpu but this one will eat 35%+ doing nothing.  Please can you find why it's doing this?  Also on the main FuckR site can you inform us all what the version is before we download rather than us blindly downloading in hope.  The software is looking better.  I noticed that when it was time for Grindr to kick me out then I managed to get back in without reloading the program but my chats  didn't seem to get through or save so I started a reload.

**Comment by gayallday** [comment]
I stopped using Bluestacks because of resource uses and moved to FuckR but right now I'd be better off on Bluestacks and that's emulating Android as well not just the Grindr software use.

**Comment by tomlandia** [comment]
OK I'll test with nw.js 0.12 vs 0.16, I think switching back to 0.12 might be enough.

**Comment by gayallday** [comment]
Did you try out the nw.js 0.12?

**Comment by tomlandia** [comment]
Closing as next release will use v0.12.
