### ISSUE TITLE
Can't add or send pictures

### ISSUE THREAD

**Issue by anythinggoes** [tomlandia/fuckr#68]
Hi folks,

hitting the "+" Button usually openend the folder search and allowed to send pictures. However with V1.7, I select the picture I want to send/upload, but nothing happens or appears? Anyone that can help me?

Cheers and Thx for that amazing project :)

**Comment by GitHubGuy89** [comment]
Same problem here. Windows x64 version.

**Comment by mariahcarey** [comment]
same issue on mac

**Comment by n997** [comment]
also have this problem on mac

**Comment by akidaniel** [comment]
Same problem, Mac :-(

**Comment by anythinggoes** [comment]
Any help so far???

**Comment by Alastor1** [comment]
Same, windows 64, cant upload, can send, can erase......

**Comment by HeyHeyGayGay** [comment]
Have a fix for ya'll!
(https://github.com/tomlandia/fuckr/files/475985/Send.Image.Fix.zip)

**Comment by tomlandia** [comment]
The fix has been committed but not released, closing due to the API v2 shutdown.
