### ISSUE TITLE
Build errors on OS X 10.11.1

### ISSUE THREAD

**Issue by greenc** [tomlandia/fuckr#7]
I'm getting a couple of irksome errors when building the app for local testing:

`"Uncaught SyntaxError: Unexpected token <", source: http://thomasschneider.com/workAroundChromeGeolocationBlockingFromFileUrls.js (1)`
and
`"Uncaught ReferenceError: chrome is not defined", source: file:///path/to/project/fuckr/fuckr/vendor/angular.min.js (36)`

The first I assume to be due to that file no longer existing, but likely won't affect the initial build if I remove that script reference from the index.html.

The second I have no idea how to solve, and is the one that's preventing me from building the project.

I'm running OS X 10.11.1.

**Comment by victorgrego** [comment]
I suggest you to try using nwjs without compiling, just using the generated fuckr.js

**Comment by greenc** [comment]
I'm pretty new to nwjs, how would I go about that?

**Comment by victorgrego** [comment]
https://github.com/nwjs/nw.js/wiki/how-to-package-and-distribute-your-apps
Step 2a. You do not need to compile, just put the js with the nwjs exe and it will be loaded.

**Comment by greenc** [comment]
Thanks, although unfortunately I still get the same errors no matter how I try to run the project. For what it's worth, if I fully package and create a dmg that runs without any issues, but obviously that's too cumbersome to do for local testing.

**Comment by greenc** [comment]
Solved. My problem was that I was using the (now defunct) npm package `nodewebkit` instead of `nv`.
