### ISSUE TITLE
Quick question

### ISSUE THREAD

**Issue by noahsmithx** [tomlandia/fuckr#71]
Hi @tomlandia , quick question: Can other users know my real location when using this? Or I'll just appear like I'm in the middle of a city let's say SF?

Thanks!

**Comment by ZeroFeetAway** [comment]
@noahsmithx Yes, your location is used just as it is within the Grindr app. Fuckr does not put you in the middle of any city or anything like that. You can however change your location by typing in another address, etc.

**Comment by noahsmithx** [comment]
Hey @ZeroFeetAway thanks for answering! I asked because in my case when I put the name of the city I am currently at, it doesn't show my real location (I triangulate my location based on the distances respect to other users). I am using a desktop so I don't think other users can know my exact location without having GPS like in a phone. Is that correct? 
I am in a big city, and it will be great if we could specify with coordinates where we are, I am not using the same account of my Grindr app, so there will appear no real known location of where I am, right? 

Have a great day!

**Comment by tomlandia** [comment]
@noahsmithx Yes it would use the location you entered.
