### ISSUE TITLE
Last active time is wrong

### ISSUE THREAD

**Issue by folmoj** [tomlandia/fuckr#72]
The last active time it displays after 1 hour appears to about double so it will appear "Active 4 hours ago" when they were actually online 2 hours ago

**Comment by Kav28** [comment]
Varies, sometimes matches.  I think there is an interval where last active is updated  "globally" and a second interval for updating during an active hour.  If the global update happens during an active time the global is changed.  If it isn't active then the global starts incrementing and will be greater than the last active time of 1 hr.  This seems to be the fuckr behavior.  App is consistent
