### ISSUE TITLE
v1.70 stopped working

### ISSUE THREAD

**Issue by gayallday** [tomlandia/fuckr#77]
It was working fine then I noticed I couldn't click on a profile picture within the mails list it would just go blank then go to the main picture line up.  When I logged out and tried to use fuckr again now it won't lot into grindr just comes up with 'unexpected error http:400 check out fuckr for updates'

**Comment by gayallday** [comment]
Grindr is suspending accounts that use FuckR whether you've signup up with FuckR or on Android.  I won't be using this software any more it's just not worth the hassles.

**Comment by Kav28** [comment]
I havent had this problem.  Only issue has been with the new upgraded
grindr - account wont start. I then install the older version and it works

**Comment by gayallday** [comment]
Well I was hoping it was just a FuckR version problem and some kind of change.  When I tried the long-term account back on Android the account is suspended.  I did nothing to warrant it other than use FuckR so I'm assuming they're not only banning new account made on FuckR but also old ones made on Android.  If that's the case then it's pointless utilizing external software.

**Comment by GitHubGuy89** [comment]
I created my account and setup my profile using my phone, and then logged onto it using Fuckr. It is still working fine, compared to accounts I created using Fuckr that were banned almost immediately.

Did you use Fuckr to update any of your profile information/settings? I think that may be what is causing the bans. I haven't touched my profile on Fuckr, only when it's logged into my phone.

**Comment by gayallday** [comment]
I was told my account had been deleted by error but then it worked with FuckR for a while longer before being deleted again.

**Comment by tomlandia** [comment]
Closing due to APIv2 shutdown.
