### ISSUE TITLE
Cannot upload any photos with V1.70

### ISSUE THREAD

**Issue by gayallday** [tomlandia/fuckr#79]
Cannot upload any photos with this new version of FuckR on a new Grindr account using windows 10

**Comment by Alastor1** [comment]
same , windows10, using fuckr 4 windows 64, cant upload, can send, can erase.....   ._.

**Comment by HeyHeyGayGay** [comment]
Got a fix for ya'll! 
(https://github.com/tomlandia/fuckr/files/475983/Send.Image.Fix.zip)

**Comment by sbpetrack** [comment]
Thaanks SO much heyheygaygay

**Comment by lolboy22** [comment]
Can somebody tell me, how to implement the fix? (sorry I am totally new to all this stuff)

**Comment by tomlandia** [comment]
The fix has been committed but not released, closing due to the API v2 shutdown.
