### ISSUE TITLE
Long replies overrun chats and prevent selection

### ISSUE THREAD

**Issue by jwax33** [tomlandia/fuckr#8]
The left side of the chat screen contains a line or two of each message you've received beside the user's picture.  They are in a bounded box you click to select that chat stream.  When you reply, your text is then shown there.

If you reply to a chat conversation above another conversation, however, and your reply is more than a couple of lines, it runs down out of the original bounded box and into the box beneath it.  If your reply is long enough, it will cover the next box entirely.  This makes it impossible to select the box underneath to read that chat message.  It will keep pulling up the chat you just responded to instead.

Leaving chat and returning does not fix it.  The application has to be restarted.

**Comment by tomlandia** [comment]
Fixed in v1.4.0 (http://fuckr.me/ will be updated in a few hours).
