### ISSUE TITLE
Can't upload pictures on Mac

### ISSUE THREAD

**Issue by charlesey** [tomlandia/fuckr#81]
I downloaded the latest version of Fuckr cause previous versions people were not getting my messages. I can't seem to upload any new pictures, it just doesn't work. Is there a fix for this?

**Comment by charlesey** [comment]
Anybody?

**Comment by salpert95** [comment]
problem exists on PC with most recent version as well.

**Comment by charlesey** [comment]
Will there be a fix to his anytime soon?

**Comment by julienenpersonne** [comment]
ref. https://github.com/tomlandia/fuckr/issues/79 corrected the problem on OSX for me

**Comment by charlesey** [comment]
How did you make the change julien?

**Comment by julienenpersonne** [comment]
@charlesey  you right click on the Fuckr App and select "Show Package Contents", then, go on the folder "Contents > Resources > app.nw > views" and replace "chat.html" by the new one in the https://github.com/tomlandia/fuckr/issues/79 issue zip file.

**Comment by charlesey** [comment]
Thanks @julienenpersonne

**Comment by tomlandia** [comment]
The fix has been committed but not released, closing due to the API v2 shutdown.
