### ISSUE TITLE
Unfriendly user message when entering wrong login details

### ISSUE THREAD

**Issue by Toldry** [tomlandia/fuckr#82]
On windows 10 64 bit version

Attempting to log in with wrong login details produces the following error message

"Please enter a valid email address or password."
Instead it should read 
"Incorrect email address or password" 
or something more clear like that

**Comment by algomez** [comment]
And all you do is log on? I just verified on Windows 10 x64. I was able to create an account successfully, log out, and log back in without incident.

**Comment by Toldry** [comment]
Exact reproduction steps:

1. Go to fuckr.me
2. Dowload and unzip the windows 10 64 bit version
3. Run fuckr.exe
4. Input emaid and password fields for a grindr account that already exist
5. Input capcha
6. Log in


Expected:
Log in


Actual:
error message "please input valid email and password"


---

Perhabs i am mistaken that fuckr is suppsode to work with a preexisting grindr account? Am i supposed to always make a new account via fuckr?

**Comment by Kav28** [comment]
Didnt have any problem doing this - did you try to clear both fields and
login again to see if its an initial connection prob?

**Comment by Toldry** [comment]
Apparently I was entering the wrong password. Woops.

I'll change the issue title to "Unfriendly user message when entering wrong login details"

Instead of "Please enter a valid email address or password."
 it should read 
"Incorrect email address or password" or something like that

**Comment by algomez** [comment]
I'm actually not sure if the Grindr API makes a distinction between
non-existant accounts and incorrect passwords. The actual Grindr app
returns the same message, regardless of whether the account exists or the
password is incorrect.

**Comment by Toldry** [comment]
Then perhaps the error message could include both scenarios
e.g.
"Wrong or invalid login details"

**Comment by tomlandia** [comment]
As of today, we just iFrame Grindr's login page and have no interest in changing their error message.
