### ISSUE TITLE
Position (top/bottom/vers)

### ISSUE THREAD

**Issue by mark-chat** [tomlandia/fuckr#86]
Is there a way of having the profile information viewable in addition to the current basics? (age, height, weight)

Particularly relevant with the latest Grindr is that it includes the facility to enter sexual preference into your profile.

You sound a bit dumb having to ask guys that crucial question: if they are top / bottom etc when it is now easily viewable on some guy's profile.........

**Comment by powline99** [comment]
To piggyback on mark's issue / request. I made this issue request in April.  ;-)

@tomlandia

1) Profile information Displayed in Table ( Missing from individual Profile Text ): Looking For / Tribe / Ethnicity / Body Type / relationship status / sexual position (existing: table w/ height/weight/age)

3) Missing as of August 2016 Prior version Fuckr Filters: Ethnicity, Height, Weight, Grindr Tribe, HIV Status, Relationship statuses" (ie. Single / open relationship)

4 ) Please Add newly added Filter Sept 2016 "Top/Bottom/Vers"

**Comment by bobbygold** [comment]
Guys,
@mark-chat  some of those filters are pulled from managed fields.  The current app is a version 2 client, the filter for the sexual position and hiv status are a version 3 filter.  The version 2 filters are pulled from https://primus.grindr.com/2.0/managedFields and the version 3 filters are pulled from https://grindr.mobi/v3/managed-fields.  This basically means that until the program is updated to version 3, you won't be able to filter the sexual position or the hiv status.

@powline99 Some of those things are not simple to pull the info for, ti would also have to be processed to be output correctly.  I put filters in myself for things like the ethnicity, which comes out as numbers.  For example, ethnicity would come out with 1 through 7, depending on the ethnicity, so these guys would also have to probably write a script to process that and then switch to the name of the field that the number corresponds with.  For example, under ethnicity, 7 equals white, when i ran that and had it in the profile, every white guy came up with the number 7.  I never bothered to write a script, and for all I know, these guys might have a simple way to make the program convert these.  I do know you can add the filter for relationship, and it will pull all the fields into the drop down list to select one and it will filter out what you select then.

**Comment by tomlandia** [comment]
Committed, will be in next release.
