### ISSUE TITLE
Entry Point Not Found

### ISSUE THREAD

**Issue by newtofuckr** [tomlandia/fuckr#92]
I downloaded the newest Fuckr from August and it would not open at all. This is the error message I got:

**"The procedure entry point GetThreadId could not be located in the dynamic link library Kernel32.dll"**

I deleted Fuckr and re-downloaded and tried to open it again, and got the same above message. 

I miss Fuckr working. It added a lot of enjoyment to my life in February and March this year, and from that point onwards, half my messages weren't being delivered, and by May, no new messages were being delivered at all. I tried in June and July to get Fuckr to work, and it never did, at which point I gave up. I thought I would try Fuckr again as of recent, but this time there are different reasons why it won't work.

Tom, I hope you can fix all the errors with the program, to make it as good as it was in Winter 2016. I blame a lot of this on Grindr. I think their corporate programmers are intentionally sabotaging and blocking a lot of your successes. I suggest you give them the metaphorical middle finger, and up your game, so that you can bypass a lot of their hurdles. :)

Looking forward to a new, better, future release.

**Comment by RobbieTechie** [comment]
@newtofuckr That sounds like an issue with your computer.  Grindr was recently updated, adn if you read the switch to API 3 issue, it has some info in there that will give some info on what you can do to get it working for now, but it's pretty much a temporary solution.
