### ISSUE TITLE
Is it possible to unblock someone?

### ISSUE THREAD

**Issue by northstar77** [tomlandia/fuckr#93]
Hi, like the subject says, I accidentally blocked someone (whoops lol) and was wondering if there is any way to unblock people? Been searching everywhere but so far don't see any options for it.

Thank you!

**Comment by Kav28** [comment]
You can unblock all in the app but not individual users.

**Comment by northstar77** [comment]
Well I know I can do it on the app, but I'm asking if it can be done through fuckr?

**Comment by paulhubert** [comment]
@northstar77 No, you cannot unblock individual users. It's not an option with the API. You either keep them blocked or unblock all. It's annoying but that's how it goes.

**Comment by ZeroFeetAway** [comment]
@northstar77  No, you cannot unblock individual users. It's not an option with the API. You either keep them blocked or unblock all. It's annoying but that's how it goes.
