### ISSUE TITLE
New version?

### ISSUE THREAD

**Issue by Bobyfridge** [tomlandia/fuckr#96]
Hello @tomlandia 
since the latest version doesn't work anymore, are there any plans for releasing a new version?

**Comment by newtofuckr** [comment]
i have not had fuckr work for me since May, as his August version never worked at all for me, so i hope he releases a version that was as good as the version from February-April 2016 :dancing_men:

**Comment by tomlandia** [comment]
[Just released](https://github.com/tomlandia/fuckr/releases/tag/1.8.0), sorry for the down period!
