### ISSUE TITLE
fuckr won't receive images

### ISSUE THREAD

**Issue by sternandbow** [tomlandia/fuckr#97]
I can send pics but not receive them. and while the pics i send are received they still show as icon symbols in the chat box. Still cannot receive images. I've installed fuckr and patched it with the recent fix and it works fine otherwise. Thanks for the help

**Comment by tomlandia** [comment]
Looks fine on [v1.8.0](https://github.com/tomlandia/fuckr/releases/tag/1.8.0), although I get rare XMPP XML parsing errors.
