### ISSUE TITLE
Miles / Kilometers Distance for USA Fuckr Users Not Working

### ISSUE THREAD

**Issue by powline99** [tomlandia/fuckr#98]
Hi @tomlandia thank you for your update, I tried the drop down and it only works in kilometers no mater what I do / logging in and out.  could @RobbieTechie collaborate with you possibly on his quick fix version. He had fixed the miles (distance for US users)  ;-) Or tell me which part of the code / files I need to share and I'll send it over.

**Comment by tomlandia** [comment]
Thanks, committed and will be in v1.8.1 along with an actual token expiration fix 🙊.
